Implementation of Payment Method Component
juice-shop/juice-shop pull request #1120
Opened 2019-06-14 05:44 UTC by agrawalarpit14

- Ability to choose from the available payment cards.
- Add new payment cards.
- Add coupon code.
- Other payment methods and Merchandise(PayPal, StickerYou).

2019-06-18 14:36 UTC, J12934 requested changes
The card UI looks really slick 👍

Some UI Consistencies I've noticed:

<img width="1174" alt="Screenshot 2019-06-18 at 16 11 52" src="https://user-images.githubusercontent.com/13718901/59692690-c9c24080-91e5-11e9-973c-5872e4576e7a.png">

Also the confirmation message is a bit weird with "ending in..." when the complete number is displayed directly under the message: 😉

<img width="798" alt="Screenshot 2019-06-18 at 16 32 49" src="https://user-images.githubusercontent.com/13718901/59693384-1d815980-91e7-11e9-9af9-010e838901f8.png">

![33qqox](https://user-images.githubusercontent.com/13718901/59693390-22dea400-91e7-11e9-86f9-3c7b5b0c3304.jpg)


I think we should also get rid of the CVV, to make sure that it is impossible to actually upload valid card numbers to JuiceShop.

What also would be nice is to have a input length display in the card number, as most users will hopefully post made up numbers this would help to input these.
There is a nice example for the on the angular material input example page:
https://material.angular.io/components/input/examples

2019-06-18 14:36 UTC, J12934 commented on routes/payment.js
> +    const cards = await models.Card.findAll({ where: { UserId: req.body.UserId } })
Noo need to do the `cards` assignment here.

2019-06-18 14:36 UTC, J12934 commented on server.js
> +app.put('/api/Cards/:id', insecurity.appendUserId(), insecurity.denyAll())
Is there a reason why `denyAll` comes after  `appendUserId()` seems weird to allow a middleware and do a denyAll afterwards.

2019-06-18 14:36 UTC, J12934 commented on server.js
> +app.put('/api/Cards/:id', insecurity.appendUserId(), insecurity.denyAll())
Actually i don't really understand whats going on here with the `appendUserId` here at all, what part of the server is using this? Especially with the Card endpoints beeing auto generated.

2019-06-21 07:42 UTC, agrawalarpit14 commented on routes/payment.js
> +    const cards = await models.Card.findAll({ where: { UserId: req.body.UserId } })
Actually, in the next line I pass it in the response, so I guess it's required.

2019-06-21 08:04 UTC, agrawalarpit14 commented on server.js
> +app.put('/api/Cards/:id', insecurity.appendUserId(), insecurity.denyAll())
I have modified it accordingly, and the `appendUserId` follows the logic as per our conversation. :wink:

2019-06-21 12:52 UTC, agrawalarpit14 commented
Hi @J12934 Please have a look on this PR as well. In this PR `saved-payment-methods` and `payment` are sharing the component `payment-methods`.

Please let me know if the implementation looks decent to you.
Thank You!!😁😁

2019-06-27 22:08 UTC, merged