[WIP] Payment component
juice-shop/juice-shop pull request #1152
Opened 2019-07-07 18:51 UTC by agrawalarpit14

- Link all views of payment component.
- Delete unused code from basket component.

2019-07-08 08:45 UTC, agrawalarpit14 commented
Hi @bkimminich Please let me know your feedback on the PR. It completes the payment component. Also, the build on GSoC is failing but IMO it will pass just by restarting the job.
Thank You!!✌🏻✌🏻😁😁

2019-07-15 14:19 UTC, bkimminich commented
@agrawalarpit14, please let me know when you had a chance to address my review comments. I'll merge soon after then!

2019-07-15 14:48 UTC, agrawalarpit14 commented
Hi @bkimminich I guess the same issue came up again, I can't see your review comments on this PR.
On my side it looks like this.

<img width="797" alt="Screenshot 2019-07-15 at 8 16 23 PM" src="https://user-images.githubusercontent.com/35000671/61225117-9075e580-a73d-11e9-8035-7c77c1592440.png">

2019-07-15 17:40 UTC, bkimminich commented
![image](https://user-images.githubusercontent.com/3531020/61236482-679f2180-a738-11e9-8f54-aaeabdf7f534.png)

2019-07-15 17:43 UTC, J12934 commented
@bkimminich you didnt submit the review ;) I can't see the comments either.

2019-07-15 17:49 UTC, bkimminich requested changes

2019-07-15 17:49 UTC, bkimminich commented on frontend/src/app/payment/payment.component.ts
> +      if (this.clientDate === new Date('Mar 08, 2019').getTime()) { // = Mar 08, 2019
Please put in the "magic number" as before - the idea here was to not spoiler the date immediately in the minified source code. Thanks!

2019-07-15 17:49 UTC, bkimminich commented on frontend/src/app/Services/basket.service.ts
> +  checkout (id?: number, couponData?: string, orderDetails?: any) {
The structure is known, so an interface instead of using `any` should be prefered.

2019-07-15 17:49 UTC, bkimminich commented on frontend/src/app/basket/basket.component.html
> +        <button id="checkoutButton" class="checkout-button" color="primary" [disabled]="productCount < 1" (click)="checkout()" mat-raised-button><i class="fas fa-cart-arrow-down"></i> {{"BTN_CHECKOUT
The donation links were moved to an inner component or are they gone now? (Just looking at the code changes from this PR, can't check entire codebase right now) - They need to show up somewhere, maybe not in the basket section but on _About Us_ or maybe in a separate screen?

2019-07-16 07:22 UTC, agrawalarpit14 commented on frontend/src/app/payment/payment.component.ts
> +      if (this.clientDate === new Date('Mar 08, 2019').getTime()) { // = Mar 08, 2019
Actually, the "magic number" is in the time zone (GMT + 1) due to which it does not matches if the person is running the application in a different time zone.
So, in the recent commit I have subtracted an offset, to make it work properly.😁😁

2019-07-16 07:24 UTC, agrawalarpit14 commented on frontend/src/app/basket/basket.component.html
> +        <button id="checkoutButton" class="checkout-button" color="primary" [disabled]="productCount < 1" (click)="checkout()" mat-raised-button><i class="fas fa-cart-arrow-down"></i> {{"BTN_CHECKOUT
Yes, they were indeed moved to an inner component in an earlier PR. It looks something like the following:

<img width="900" alt="Screenshot 2019-07-16 at 12 53 45 PM" src="https://user-images.githubusercontent.com/35000671/61274131-c14f2c80-a7c8-11e9-84c9-a4d45d4a8605.png">

2019-07-16 08:31 UTC, bkimminich commented on frontend/src/app/payment/payment.component.ts
> +      if (this.clientDate === new Date('Mar 08, 2019').getTime()) { // = Mar 08, 2019
Brilliant! 👍

2019-07-16 11:24 UTC, agrawalarpit14 commented
Hi @bkimminich Please have a look on this PR.
Thank you so much!!😁😁

2019-07-16 13:41 UTC, merged