Add memory to data export, add twitter button
juice-shop/juice-shop pull request #1186
Opened 2019-08-08 13:35 UTC by agrawalarpit14

2019-08-08 14:40 UTC, bkimminich requested changes

2019-08-08 14:40 UTC, bkimminich commented on frontend/src/app/order-completion/order-completion.component.html
> +            <a href="https://twitter.com/intent/tweet?text={{ tweetText }}&hashtags=security&url=https://juice-shop.herokuapp.com">
Hardcoding this is not okay, it would have to be the URL of the actual server _or_ some configurable URL _or_ no URL at all.

2019-08-08 14:40 UTC, bkimminich commented on frontend/src/app/order-completion/order-completion.component.ts
> +        this.tweetText += '@owasp_juiceshop'
Use `@` plus the last part of `application.twitterUrl` from configuration instead. If `twitterUrl` does not exist, do not add mention at all.

2019-08-08 14:40 UTC, bkimminich commented on frontend/src/app/photo-wall/photo-wall.component.html
> +                        <a href="https://twitter.com/intent/tweet?text={{ image.caption }} @owasp_juiceshop&hashtags=security&url=https://juice-shop.herokuapp.com">
See comments above. No static references to Juice Shop please, this breaks customization.

2019-08-08 17:53 UTC, agrawalarpit14 commented on frontend/src/app/order-completion/order-completion.component.html
> +            <a href="https://twitter.com/intent/tweet?text={{ tweetText }}&hashtags=security&url=https://juice-shop.herokuapp.com">
Sure, I have removed the `URL` as if the person needs to actually use `URL`, they can add it before clicking the tweet button.😁😅

2019-08-09 15:28 UTC, bkimminich approved these changes

2019-08-09 15:28 UTC, merged