Add exposed metrics challenge
juice-shop/juice-shop pull request #1299
Opened 2020-02-10 21:01 UTC by Scar26

Created a new endpoint at /api/metrics that serves metrics for Prometheus. User simply needs to access it to solve the challenge

Solves : #1275

2020-02-10 21:43 UTC, J12934 requested changes
This looks really nice 👍

I‘ve noticed some small(ish) things while looking at the code. Hoping these show up correctly in the review. First time for me submitting a PR review via the new GitHub mobile app 🤞

One other thing, this registers the metrics endpoint under `/api/metrics` instead of the default `/metrics` if I saw correctly. Was that a intentional choice, if so I‘d loved to know why. Would have personally put it just under the default `/metrics`, especially for a one star difficulty rating.

Also please take a look at the DCO check.
Also the Travis builds seems to be failing, can’t look at the logs easily on the mobile version, might be that the new tests are actually failing.

2020-02-10 21:43 UTC, J12934 commented on routes/metrics.js
> +    return [register, intervalCollector]
Any reason to export this as an array instead of an object?
This seems especially cumbersome when imported in the `server.js` file.

2020-02-10 21:43 UTC, J12934 commented on server.js
> +metricsProbe = Metrics[1]
Unused?

2020-02-10 21:43 UTC, J12934 commented on test/api/metricsAPISpec.js
> +        return frisby.get(METRICS_URL).expect('status',200)
Where‘s the `METRICS_URL` var coming from?

2020-02-10 21:43 UTC, J12934 commented on routes/metrics.js
> +  const orderMetrics = new Prometheus.Gauge({
I think in Prometheus terms these three custom metrics should all rather be counters, as these are values which can only go up. Minor thought.

2020-02-10 21:43 UTC, J12934 commented on routes/metrics.js
> +  setInterval(() => {
Might be worth it to export the interval to clear it in the server shutdown.
Just to ensure a clean exit.

2020-02-10 21:43 UTC, J12934 commented on test/api/metricsAPISpec.js
> +
👍 Really nice that you‘ve added test 👏

Have you looked into weather there is a easy way to parse the output of the Prometheus metrics?
Would be cool to have an assertion which can cheat that the custom metrics work as intended.

2020-02-11 02:29 UTC, Scar26 commented on routes/metrics.js
> +    return [register, intervalCollector]
No particular reason, just originally had a slightly different workflow in mind.
Will change this right away

2020-02-11 02:31 UTC, Scar26 commented on server.js
> +metricsProbe = Metrics[1]
Removed in the last commit. I accidentally left out some minor changes and pushed them with the linting errors commit

2020-02-11 02:31 UTC, Scar26 commented on test/api/metricsAPISpec.js
> +        return frisby.get(METRICS_URL).expect('status',200)
Fixed in the last commit

2020-02-11 02:42 UTC, Scar26 commented on routes/metrics.js
> +  const orderMetrics = new Prometheus.Gauge({
But wouldn't using gauges give us more flexibility with future challenges. For example, there might be a challenge where you have to delete a user(this challenge already exists I think) or delete one of your orders from the logs. This would make the values go down.

Will change the challengeMetriccs to Counter

2020-02-11 02:44 UTC, Scar26 commented on routes/metrics.js
> +  setInterval(() => {
Sorry, I'm not sure I understand this. 
The obersveMetrics function, inside which this setinterval is called is already called from within server.js

2020-02-11 02:45 UTC, Scar26 commented on test/api/metricsAPISpec.js
> +
Ok, cool!
I'll get to it

2020-02-11 03:15 UTC, Scar26 commented on routes/metrics.js
> +  const orderMetrics = new Prometheus.Gauge({
Looks like there is no function in the prom-client module to directly set the value if a counter, it can only be increased by a given value. I have not-so-elegant workaround for this in mind, increasing it by (new number - current value). Should I implement this?

2020-02-11 12:26 UTC, J12934 commented on routes/metrics.js
> +  const orderMetrics = new Prometheus.Gauge({
Okay. Not that big of a problem.
Then we'll just leave it as gauges.

2020-02-11 12:45 UTC, J12934 requested changes

2020-02-11 12:45 UTC, J12934 commented on config.schema.yml
> +    exposedMetricsChallenge:
What are these config values for?

2020-02-11 12:45 UTC, J12934 commented on routes/metrics.js
> +  const intervalCollector = Prometheus.collectDefaultMetrics({ prefix: 'juice_shop_', timeout: 5000, register })
Would remove the prefix for the default metrics.
Without the prefix users could just use prebuild grafana dashboards for nodejs apps.

With the prefix these would not be compatible.
To identify the metrics would recommend setting a default `app` label like so:

```js
register.setDefaultLabels({ app: 'juice-shop' })
```

2020-02-11 12:45 UTC, J12934 commented on routes/metrics.js
> +    name: 'no_of_orders_placed',
The custom metrics should actually be prefixed ;)

According to [prometheus naming conventions](https://prometheus.io/docs/practices/naming/) this should rather be named: `juiceshop_orders_placed_total`

2020-02-11 12:45 UTC, J12934 commented on routes/metrics.js
> +    name: 'no_of_challenges_solved',
Should be `juiceshop_challenges_solved_total`

2020-02-11 12:45 UTC, J12934 commented on routes/metrics.js
> +    name: 'no_of_users_registered',
Should be `juiceshop_users_registered_total`

2020-02-11 12:45 UTC, J12934 commented on routes/metrics.js
> +  setInterval(() => {
Yes, i meant to [clear the interval](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearInterval) when the server is shutdown.
(See https://github.com/bkimminich/juice-shop/blob/master/server.js#L519)

This isn't super required, as they should stop as soon as node stops, but its always a good idea to cleanup things explicitly.

2020-02-11 17:31 UTC, Scar26 commented on config.schema.yml
> +    exposedMetricsChallenge:
The lint tests are telling me that there should be a country mapping for every challenge.

It's also telling me to update config/fbctf.yml

I don't understand what this is, what should I do, should I just map it to some random country?

2020-02-11 17:47 UTC, J12934 commented on config.schema.yml
> +    exposedMetricsChallenge:
Yes

2020-02-11 21:24 UTC, Scar26 commented on test/api/metricsAPISpec.js
> +
Made a few changes, does this work?
Checking if it's returning the correct values would be a bit tricky because number of orders is returned asynchronously and there would also be a race condition between update in data-cache and the returned metrics but can be done if necessary. I'll try to implement this as soon as possible

2020-02-11 21:24 UTC, Scar26 commented on routes/metrics.js
> +  setInterval(() => {
Done

2020-02-11 21:24 UTC, Scar26 commented on config.schema.yml
> +    exposedMetricsChallenge:
Done

2020-02-11 21:24 UTC, Scar26 commented on routes/metrics.js
> +  const intervalCollector = Prometheus.collectDefaultMetrics({ prefix: 'juice_shop_', timeout: 5000, register })
Done

2020-02-11 21:24 UTC, Scar26 commented on routes/metrics.js
> +    name: 'no_of_orders_placed',
Done

2020-02-11 21:25 UTC, Scar26 commented on routes/metrics.js
> +    name: 'no_of_challenges_solved',
Done

2020-02-11 21:32 UTC, J12934 commented on test/api/metricsAPISpec.js
> +
This looks like a good solution. I‘ll try to give it another look tomorrow but I think this is about ready to go 👍

2020-02-11 21:33 UTC, J12934 commented
@Scar26 can you take a look at the DCO Check?
The commits need to be signed off before they can be merged

2020-02-11 22:32 UTC, Scar26 commented
DCO test is now verified.

Tried around for a while, couldn't find the proper way to do it so I just did a soft reset and force push.
Will be careful while committing from now on

2020-02-12 09:26 UTC, Scar26 commented
@J12934 The build is throwing a very unexpected error specifically on mac + node 12

On a sidenote, maybe I can also just get rid of the e2e test for metrics challenge. Because the API test already checks that the route is working and if it is, the challenge most likely works fine

2020-02-12 11:09 UTC, bkimminich commented
Every challenge needs to be verifiable via an e2e test, because challenges are the core of Juice Shop. If they don't work we need to reliably know about it.

2020-02-12 11:35 UTC, Scar26 commented
All right!
I'll try to fix this ASAP.
Though I don't understand why the tests are failing specifically on Mac and node 12 when all I did was disable the angular check before a request, when this is already being done in some other tests.

2020-02-12 14:51 UTC, Scar26 commented
Looks like the e2e test is actually working fine.

![metricse2e](https://user-images.githubusercontent.com/41830515/74346216-3e7d6700-4dd5-11ea-92aa-e61700c57aa1.png)

2020-02-12 15:07 UTC, J12934 commented
I‘ve restarted the failing Mac build. Might fix it if is flaky

2020-02-12 15:56 UTC, Scar26 commented
@J12934 It passed this time

2020-02-12 16:41 UTC, J12934 approved these changes

2020-02-12 17:47 UTC, merged