Add ChatBot API
juice-shop/juice-shop pull request #1420
Opened 2020-07-01 19:26 UTC by Scar26

2020-07-02 11:49 UTC, bkimminich requested changes

2020-07-02 11:49 UTC, bkimminich commented on config/default.yml
> +  chatBot:
Making bot name and training data configurable seems reasonable to me, but the greeting and test command/response somehow feel overkill to be configurable. Is this really necessary?

2020-07-02 11:49 UTC, bkimminich commented on routes/updateUserProfile.js
> +        user.update({ username: req.body.username }).then(newuser => {
Would this actually update the JWT `Authorization: Bearer` header as well? I'm not sure right now...

2020-07-02 11:55 UTC, Scar26 commented on routes/updateUserProfile.js
> +        user.update({ username: req.body.username }).then(newuser => {
I'm returning it in the token cookie. The token in the auth header is also retrieved from the cookie I believe, and the insecurity.updateAuthenticatedUsers middleware  updates it in sessions as well

2020-07-02 12:14 UTC, Scar26 commented on config/default.yml
> +  chatBot:
it's needed in the unit tests. If someone is deploying their own instance of juice-shop they might wanna provide their own trainingData, in which case the unit tests would need to be changed as well. That's why I decided to make all params configurable

But I guess if someone is changing training data, they can probably change the file by themselves as well. Should I remove this from config then?

2020-07-04 14:04 UTC, bkimminich commented on config/default.yml
> +  chatBot:
Okay, I took a deeper look into this. I see two possible solutions:

1. We do not test the chat bot in the Juice Shop but rely on its own tests in the `juicy-chat-bot` repo (with the ones here being essentially equal) - Pro: easy / Con: no tests 😁 
2. We pull the information needed for the test from the training set file itself instead of duplicating the commands in the config. This would be easy for the default set, but harder for a custom one, so we might have to set some rule for a mandatory set entry for testing in the training set file. Pro: tests / Con: some extra work 😃

I prefer 2.) but could live with 1.) as well. On the other hand we need to add some kind of tests at some point when the bot gets its own challenges - and those need to work with custom training data as well - so, maybe this is a good exercise early on for testing the bot inside Juice Shop.

2020-07-11 18:16 UTC, bkimminich commented
The smoke test with the ZIP archive fails because the training set is not added to it in `Gruntfile.js`. I would recommend to move the file into the `data/static` folder and name it `chatbotTrainingData.json` instead of giving it its own subfolder. For an example how to handle files that can be replaced by custom files best check how the `data/static/JuiceShopJingle.vtt` is being handled.

2020-07-12 12:14 UTC, merged