One click deploy for platform.sh
juice-shop/juice-shop pull request #1578
Opened 2021-02-01 16:28 UTC by robertobarreda

Added configuration files for one-click deployment on [Platform.sh](https://platform.sh/)

2021-02-01 17:30 UTC, bkimminich commented
@J12934: Are you familiar with `platform.sh`? In case you are, could take a look at this PR please?

@robertobarreda: If that works, we could have the button on the main README similar to the Heroku button and ditch the sub-README in favor of just a 1.,2.,3. etc. of steps to do. Bascially same as with all the other deploy instrustions.

2021-02-01 17:33 UTC, bkimminich commented
Will this deploy button honor the branch you're currently on or always deploy `master`? Is there maybe even a way to make it work with forks? The Heroku button can do that. That's not mandatory to merge the PR, would just be nice. If it doesn't work like that, the instruction steps should say so, because otherwise false expectations might be generated (as people are used to the Heroku button behavior).

2021-02-01 21:17 UTC, J12934 commented
Haven't used it before. 
But I'll still take a look at it 👨‍💻

2021-02-02 10:25 UTC, robertobarreda commented
Thanks @bkimminich for the time to take a look at the PR

> Will this deploy button honor the branch you're currently on or always deploy `master`? Is there maybe even a way to make it work with forks? The Heroku button can do that. That's not mandatory to merge the PR, would just be nice. If it doesn't work like that, the instruction steps should say so, because otherwise false expectations might be generated (as people are used to the Heroku button behavior).

According to the [documentation](https://docs.platform.sh/frameworks/deploy-button.html#arbitrary-git-repository), any fork will need to replace the `template` parameter to work.

It is not in the documentation but you can pass any branch to the URL to create the initial project:
`https://console.platform.sh/projects/create-project?template=GIT_URL@GIT_BRANCH`

I'll try to talk with the people at @platformsh to add support for the `referer` header.

I didn't change the README because I thought you'd prefer to first take a look at the feature.

2021-02-02 21:34 UTC, J12934 commented
Tried it out, but initial build didn't go through. (Replaced the repo reference in the link with the fork)

Angular build exited with 137, I'd suspect it was OOM killed. (out of memory)
Did this step complete for you @robertobarreda? Do you know if there is a way to increase the size of the "box" building the application?

```txt
      > juice-shop@12.5.0 build /app
      > cd frontend && node ./node_modules/@angular/cli/bin/ng build --aot --prod --output-hashing=none --vendor-chunk=true --source-map=false
      
      W: Warning: Using differential loading with targets ES5 and ES2016 or higher may
      W: cause problems. Browsers with support for ES2015 will load the ES2016+ scripts
      W: referenced with script[type="module"] but they may not support ES2016+ syntax.
      W: - Generating browser application bundles...
      W: ✔ Browser application bundle generation complete.
      W: - Generating ES5 bundles for differential loading...
      W: Killed
      W: npm ERR! code ELIFECYCLE
      W: npm ERR! errno 137
      W: npm ERR! juice-shop@12.5.0 build: `cd frontend && node ./node_modules/@angular/cli/bin/ng build --aot --prod --output-hashing=none --vendor-chunk=true --source-map=false`
      W: npm ERR! Exit status 137
      W: npm ERR! 
      W: npm ERR! Failed at the juice-shop@12.5.0 build script.
      W: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
      W: 
      W: npm ERR! A complete log of this run can be found in:
      W: npm ERR!     /mnt/cache/npm/_logs/2021-02-02T21_27_10_477Z-debug.log
      W: npm ERR! code ELIFECYCLE
      W: npm ERR! errno 137
      W: npm ERR! juice-shop@12.5.0 postinstall: `cd frontend && npm install && cd .. && npm run build`
      W: npm ERR! Exit status 137
      W: npm ERR! 
      W: npm ERR! Failed at the juice-shop@12.5.0 postinstall script.
      W: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
      W: 
      W: npm ERR! A complete log of this run can be found in:
      W: npm ERR!     /mnt/cache/npm/_logs/2021-02-02T21_27_12_323Z-debug.log
      W: 0
    
    E: Error building project: `npm` could not be run.

E: Error: Unable to build application, aborting.
```

<details>
  <summary>Full Logs</summary>
  
```
   Found 1 commit
 
   Building application 'app' (runtime type: nodejs:12, tree: f757778)
     Generating runtime configuration.
     
     Building a NodeJS application, let's make it fly.
     Found a `package.json`, installing dependencies.
       W: npm WARN deprecated jsonwebtoken@0.4.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
       W: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
       W: npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
       W: npm WARN deprecated jsonwebtoken@0.1.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
       W: npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
       W: npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
       W: npm WARN deprecated jws@0.2.6: Security update: Versions below 3.0.0 are deprecated.
       W: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
       W: npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
       W: npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
       W: npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
       W: npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
       W: npm WARN deprecated eivindfjeldstad-dot@0.0.1: Use @eivifj/dot instead
       W: npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
       W: npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
       W: npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
       W: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
       W: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
       
       > iltorb@2.4.5 install /app/node_modules/iltorb
       > node ./scripts/install.js || node-gyp rebuild
       
       W: info looking for cached prebuild @ /mnt/cache/npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
       W: http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v72-linux-x64.tar.gz
       W: http 200 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v72-linux-x64.tar.gz
       W: info downloading to @ /mnt/cache/npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz.121-3b689c42473a4.tmp
       W: info renaming to @ /mnt/cache/npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
       W: info unpacking @ /mnt/cache/npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
       W: info unpack resolved to /app/node_modules/iltorb/build/bindings/iltorb.node
       W: info unpack required /app/node_modules/iltorb/build/bindings/iltorb.node successfully
       W: info install Successfully installed iltorb binary!
       
       > libxmljs2@0.26.6 install /app/node_modules/libxmljs2
       > node-pre-gyp install --fallback-to-build --loglevel http
       
       W: node-pre-gyp WARN Using request for node-pre-gyp https download 
       W: node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.26.6/node-v72-linux-x64-glibc.tar.gz
       W: node-pre-gyp http 200 https://github.com/marudor/libxmljs2/releases/download/v0.26.6/node-v72-linux-x64-glibc.tar.gz
       [libxmljs2] Success: "/app/node_modules/libxmljs2/build/Release/xmljs.node" is installed via remote
       
       > sqlite3@5.0.1 install /app/node_modules/sqlite3
       > node-pre-gyp install --fallback-to-build
       
       W: node-pre-gyp WARN Using request for node-pre-gyp https download 
       W: node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz 
       W: node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@12.18.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
       make: Entering directory '/app/node_modules/sqlite3/bu [...]

2021-02-03 10:43 UTC, robertobarreda commented
> Tried it out, but initial build didn't go through. (Replaced the repo reference in the link with the fork)
> 
> Angular build exited with 137, I'd suspect it was OOM killed. (out of memory)
> Did this step complete for you @robertobarreda? Do you know if there is a way to increase the size of the "box" building the application?
> 
> ```
>       > juice-shop@12.5.0 build /app
>       > cd frontend && node ./node_modules/@angular/cli/bin/ng build --aot --prod --output-hashing=none --vendor-chunk=true --source-map=false
>       
>       W: Warning: Using differential loading with targets ES5 and ES2016 or higher may
>       W: cause problems. Browsers with support for ES2015 will load the ES2016+ scripts
>       W: referenced with script[type="module"] but they may not support ES2016+ syntax.
>       W: - Generating browser application bundles...
>       W: ✔ Browser application bundle generation complete.
>       W: - Generating ES5 bundles for differential loading...
>       W: Killed
>       W: npm ERR! code ELIFECYCLE
>       W: npm ERR! errno 137
>       W: npm ERR! juice-shop@12.5.0 build: `cd frontend && node ./node_modules/@angular/cli/bin/ng build --aot --prod --output-hashing=none --vendor-chunk=true --source-map=false`
>       W: npm ERR! Exit status 137
>       W: npm ERR! 
>       W: npm ERR! Failed at the juice-shop@12.5.0 build script.
>       W: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>       W: 
>       W: npm ERR! A complete log of this run can be found in:
>       W: npm ERR!     /mnt/cache/npm/_logs/2021-02-02T21_27_10_477Z-debug.log
>       W: npm ERR! code ELIFECYCLE
>       W: npm ERR! errno 137
>       W: npm ERR! juice-shop@12.5.0 postinstall: `cd frontend && npm install && cd .. && npm run build`
>       W: npm ERR! Exit status 137
>       W: npm ERR! 
>       W: npm ERR! Failed at the juice-shop@12.5.0 postinstall script.
>       W: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>       W: 
>       W: npm ERR! A complete log of this run can be found in:
>       W: npm ERR!     /mnt/cache/npm/_logs/2021-02-02T21_27_12_323Z-debug.log
>       W: 0
>     
>     E: Error building project: `npm` could not be run.
> 
> E: Error: Unable to build application, aborting.
> ```
> 
> Full Logs
> ```
>    Found 1 commit
>  
>    Building application 'app' (runtime type: nodejs:12, tree: f757778)
>      Generating runtime configuration.
>      
>      Building a NodeJS application, let's make it fly.
>      Found a `package.json`, installing dependencies.
>        W: npm WARN deprecated jsonwebtoken@0.4.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
>        W: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
>        W: npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
>        W: npm WARN deprecated jsonwebtoken@0.1.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
>        W: npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
>        W: npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
>        W: npm WARN deprecated jws@0.2.6: Security update: Versions below 3.0.0 are deprecated.
>        W: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
>        W: npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
>        W: npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
>        W: npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
>        W: npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
>        W: npm WARN deprecated eivindfjeldstad-dot@0.0.1: Use @eivifj/dot instead
>        W: npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
>        W: npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
>        W: npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
>        W: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
>        W: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
>        
>        > iltorb@2.4.5 install /app/node_modules/iltorb
>        > node ./scripts/install.js || node-gyp rebuild
>        
>        W: info looking for cached prebuild @ /mnt/cache/npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
>        W: http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v72-linux-x64.tar.gz
>        W: http 200 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v72-linux-x64.tar.gz
>        W: info downloading to @ /mnt/cache/npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz.121-3b689c42473a4.tmp
>        W: info renaming to @ /mnt/cache/npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
>        W: info unpacking @ /mnt/cache/npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
>        W: info unpack resolved to /app/node_modules/iltorb/build/bindings/iltorb.node
>        W: info unpack required /app/node_modules/iltorb/build/bindings/iltorb.node successfully
>        W: info install Successfully installed iltorb binary!
>        
>        > libxmljs2@0.26.6 install /app/node_modules/libxmljs2
>        > node-pre-gyp install --fallback-to-build --loglevel http
>        
>        W: node-pre-gyp WARN Using request for node-pre-gyp https download 
>        W: node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.26.6/node-v72-linux-x64-glibc.tar.gz
>        W: node-pre-gyp http 200 https://github.com/marudor/libxmljs2/releases/download/v0.26.6/node-v72-linux-x64-glibc.tar.gz
>        [libxmljs2] Success: "/app/node_modules/libxmljs2/build/Release/xmljs.node" is installed via remote
>        
>        > sqlite3@5.0.1 install /app/node_modules/sqlite3
>        > node-pre-gyp install --fallback-to-build
>        
>        W: node-pre-gyp WARN Using request for node-pre-gyp https download 
>        W: node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz 
>        W: node-pre-gyp WARN Pre-built binaries not found for sql [...]

2021-02-10 15:55 UTC, bkimminich commented
![image](https://user-images.githubusercontent.com/3531020/107535115-bdf86e80-6bc0-11eb-9cff-8326b447654a.png)

Correct me if I'm wrong, but currently all the deployment options we have instructions for offer some kind of free tier, so even on AWS/Azure/GCP you could run Juice Shop for free on a tiny node. I never tried GCP myself, so I can't tell for that one. And Azure at some point wanted money from me, I recall that. But at least you could at least start for free. Platform.sh wants me to get a Developer plan for 10$ right from the start before I can even deploy. Now here's the thing: If someone uses our instructions, sets up that plan, and then it won't work or at least not consistently compile, they could (somewhat rightfully) get angry at us because we "advertised" it as a supported platform. Unless there is a hidden free tier available somehow, I don't think I want to include this into the official docs, tbh. ...

2021-02-10 15:58 UTC, bkimminich commented
If you put up these instructions elsewhere (blog post, gist, ...) I'm happy to refer to that from our `REFERENCES.md` - that's totally fine, as it's not "official" then, just part of our collection of links and references. So, no angry plahform.sh-mob showing up on our doorstep if it's not 100% stable, y'know... :-)

2021-02-10 16:01 UTC, Crell commented
Platform.sh dev plans are free for the first month for a new user.  There is no perma-free tier at this point.

2021-02-15 19:27 UTC, bkimminich commented
Okay, so I clicked through the process now until project creation happens. Deployment fails because of repo reference, but all-in-all I'd be fine with adding this option to the deploy options in the README and eBook (other repo, I'll copy it over there once this PR is merged). In order to merge this PR please change it as follows:

1. Remove the default README from platform.sh
2. Add step-by-step guide (as short as possible but not leaving out any non-trivial steps, see existing guides) to main README as new last subsection of https://github.com/bkimminich/juice-shop#setup named "Platform.sh"
3. Add the deploy button after the step-by-step guide (like in Heroku section) but statically point to `master` in its URL
4. Please also add a quote at the end of the new section (similar also to Heroku section) stating "The deploy button above is not context aware and will always deploy the `master` branch of `bkimminich/juice-shop`. You have to alter the URL of the button as needed to deploy another branch or fork."

Thanks a lot & cheers!

2021-02-15 19:29 UTC, bkimminich requested changes
Please see https://github.com/bkimminich/juice-shop/pull/1578#issuecomment-779411497.

2021-02-16 11:02 UTC, robertobarreda commented
> Okay, so I clicked through the process now until project creation happens. Deployment fails because of repo reference, but all-in-all I'd be fine with adding this option to the deploy options in the README and eBook (other repo, I'll copy it over there once this PR is merged). In order to merge this PR please change it as follows:
> 
> 1. Remove the default README from platform.sh
> 2. Add step-by-step guide (as short as possible but not leaving out any non-trivial steps, see existing guides) to main README as new last subsection of https://github.com/bkimminich/juice-shop#setup named "Platform.sh"
> 3. Add the deploy button after the step-by-step guide (like in Heroku section) but statically point to `master` in its URL
> 4. Please also add a quote at the end of the new section (similar also to Heroku section) stating "The deploy button above is not context aware and will always deploy the `master` branch of `bkimminich/juice-shop`. You have to alter the URL of the button as needed to deploy another branch or fork."
> 
> Thanks a lot & cheers!

I'll check your requirements and come back to you as soon as possible. Many thanks!

2021-02-27 14:13 UTC, bkimminich commented
I'm closing this PR as it seems to have gone stale. Please feel free to open a new one in the form described in https://github.com/bkimminich/juice-shop/pull/1578#issuecomment-779411497 to the `develop` branch. Thanks!

2021-02-27 14:13 UTC, closed without merging