added new data-erasure route
juice-shop/juice-shop pull request #1586
Opened 2021-02-20 02:18 UTC by cigar-galaxy82

https://user-images.githubusercontent.com/56212958/108580097-04cc2e00-7350-11eb-905d-d7ce6890e866.mp4

2021-02-20 15:15 UTC, bkimminich commented
Awesome! I'll test the new screen and review the code next week! First impression is very good! 👍

2021-02-22 10:42 UTC, bkimminich requested changes

2021-02-22 10:42 UTC, bkimminich commented on test/api/dataErasureApiSpec.js
> +  it('GET data-erasure page', () => {
Copy/paste mistake?

2021-02-22 10:42 UTC, bkimminich commented on frontend/src/app/navbar/navbar.component.html
> +      <button mat-menu-item (click) = "goToDataErasurePage()" aria-label="Go to data subject page">
Similar change is also needed in sidenav component (used on smaller screens)

2021-02-22 10:42 UTC, bkimminich commented on views/data-erasure.hbs
> +<meta charset="UTF-8">
Clicking on "Delete user data" button without entering any data gives a funny screen duplication effect. Also works multiple times in a row, see screenshot:
![image](https://user-images.githubusercontent.com/3531020/108696990-911e5280-7502-11eb-88e4-d98a87fa3760.png)

2021-02-22 10:42 UTC, bkimminich commented on views/data-erasure.hbs
> +		<button class="uppercase px-8 py-2 rounded border border-green-600 text-green-600 max-w-max shadow-sm hover:shadow-lg" type="submit">Delete User Data</button>
On the Angular screen there was a feedback message (in the snackbar) displayed when the deletion request was sent. There is no more feedback for the user from the HBS screen, not when returning to the Angular client also not on the HBS screen itself.

2021-02-22 11:10 UTC, cigar-galaxy82 commented on views/data-erasure.hbs
> +		<button class="uppercase px-8 py-2 rounded border border-green-600 text-green-600 max-w-max shadow-sm hover:shadow-lg" type="submit">Delete User Data</button>
I display the message "Sorry to see to leave" with the go to home button in place of that

2021-02-22 13:42 UTC, cigar-galaxy82 commented on test/api/dataErasureApiSpec.js
> +  it('GET data-erasure page', () => {
yes I will change the code then create a new pull request

2021-02-22 13:45 UTC, cigar-galaxy82 commented on frontend/src/app/navbar/navbar.component.html
> +      <button mat-menu-item (click) = "goToDataErasurePage()" aria-label="Go to data subject page">
solved

2021-02-22 13:46 UTC, cigar-galaxy82 commented on views/data-erasure.hbs
> +<meta charset="UTF-8">
I added a feature where button will be disabled until both the input block contain value

2021-02-23 08:16 UTC, closed without merging