Fix: Race Condition resolved with I18n files on server starts.
juice-shop/juice-shop pull request #1587
Opened 2021-02-22 06:49 UTC by adityaofficial10

Fixes #1585 
What does this PR do?
This PR fixes issue #1585 to resolve the race condition between file reset and configuration of i18n files.

Steps taken:
Two asynchronous functions configureI18n() and reloadI18nFiles() have been added to ensure that the file copying process finishes before configuring I18n.
<img width="881" alt="fix" src="https://user-images.githubusercontent.com/65034276/108672194-ae095480-7507-11eb-8648-3f9d6a3c336e.png">

2021-02-22 09:13 UTC, J12934 requested changes
Looks good 👍
But requires some further tweeks

2021-02-22 09:13 UTC, J12934 commented on server.js
> +async function reloadI18nFiles () {
I think it would be better just name this wrapper function `restoreOverwrittenFilesWithOriginals`, otherwise there are two names for this functionality.

2021-02-22 09:13 UTC, J12934 commented on server.js
> +  collectDurationPromise('restoreOverwrittenFilesWithOriginals', require('./lib/startup/restoreOverwrittenFilesWithOriginals'))()
This needs to be awaited. Otherwise we'd still have the race condition

```suggestion
  await collectDurationPromise('restoreOverwrittenFilesWithOriginals', require('./lib/startup/restoreOverwrittenFilesWithOriginals'))()
```

2021-02-22 09:13 UTC, J12934 commented on server.js
> +async function configureI18n () {
This function doesn't need to be async.

2021-02-22 09:52 UTC, adityaofficial10 commented
@J12934 
Thanks for reviewing..
I'll make the necessary changes and commit here..

2021-02-22 10:56 UTC, bkimminich requested changes
I ran `npm frisby` and ended up with every `500` errors instead of expected `200`s. When I `npm start`ed the server and browsed to the main page, I get these errors in the console:

```
TypeError: req.__ is not a function
    at C:\Data\GitHub\juice-shop\routes\search.js:52:34
TypeError: req.__ is not a function
    at List.<anonymous> (C:\Data\GitHub\juice-shop\server.js:463:49)
    at runHookFunction (C:\Data\GitHub\juice-shop\node_modules\finale-rest\lib\Controllers\base.js:147:44)
    at tryCatcher (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
info: Solved 1-star errorHandlingChallenge (Error Handling)
info: Cheat score for trivial errorHandlingChallenge solved in 0 / 0 minutes with hints allowed: 0
TypeError: req.__ is not a function
    at List.<anonymous> (C:\Data\GitHub\juice-shop\server.js:463:49)
    at runHookFunction (C:\Data\GitHub\juice-shop\node_modules\finale-rest\lib\Controllers\base.js:147:44)
    at tryCatcher (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Data\GitHub\juice-shop\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

![image](https://user-images.githubusercontent.com/3531020/108698595-97adc980-7504-11eb-899d-8a2864b0d807.png)

The `req.__` function that is missing is the one which `i18n` adds to all requests for access to translations. I suppose the initialization did not complete. Btw, I was waiting for like 10sec after restart before requesting the page, so the server had enough time to complete everything.

2021-02-22 11:00 UTC, adityaofficial10 commented
@bkimminich 
I'll go through the code again and do the needful.
Thanks.

2021-02-22 11:48 UTC, adityaofficial10 commented
@bkimminich 
Can you tell me what purpose does that portion of code serve?
I think we'll have to wrap that up in a separate async function so that it occurs after i18n is configured.
So to name the function, I'll need the purpose.

2021-02-22 11:49 UTC, adityaofficial10 commented on server.js
> +async function configureI18n () {
@J12934 
I just made that async so as to ensure that it executes after reloading has finished..

2021-02-22 11:53 UTC, bkimminich commented
That code is part of the `i18n` module, not of Juice Shop. We just use this as a feature. I guess wrapping the configuration of i18n into async had some side effect with Express. But your guess is as good as mine here.

2021-02-22 16:05 UTC, J12934 commented on server.js
> +async function configureI18n () {
Okay but this has nothing to do with the order.
That is ensured by the `await` in the `await reloadI18nFiles()` statement.

This ensures that the following statements only run after the promise it returns are completed, no matter if these functions are async or not.

2021-02-22 20:10 UTC, adityaofficial10 commented
@J12934 
I've changed the function name and its nature as instructed.
@bkimminich 
As for the approach, I tried using then() and it works perfectly.
I ran the tests locally and they passed.
So is this fine now?
<img width="954" alt="Screenshot 2021-02-23 at 1 35 45 AM" src="https://user-images.githubusercontent.com/65034276/108764021-142dc000-7578-11eb-809e-3afaf4219b3d.png">

2021-02-24 19:35 UTC, bkimminich commented
Just tried it locally and so far works fine. I've merged latest `develop` back into your fork and will merge the PR if CI/CD passed. Thanks a lot!

PS: If you send me your post address I'll send you a few stickers as a _thank you!_ for your first merged PR!

2021-02-24 19:38 UTC, adityaofficial10 commented
@bkimminich 
Thanks a lot for that.
I'd also like to discuss this OWASP GSoC idea related to juice shop.
So Can I contact you directly for the same or through the mailing lists?

2021-02-24 19:39 UTC, bkimminich commented
You can write me an email or DM me on Slack or Gitter, sure!

2021-02-24 19:40 UTC, adityaofficial10 commented
Great!
Thanks a lot..
I'll analyse the idea a bit more and reach out to you..

2021-02-24 21:11 UTC, merged