make changes required
juice-shop/juice-shop pull request #1593
Opened 2021-03-01 14:08 UTC by cigar-galaxy82

2021-03-01 18:16 UTC, J12934 requested changes

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
Axios doesn't appear to be actually used on this page

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +					    url: 'http://localhost:3000/dataerasure',
hardcoded local url...

2021-03-01 18:16 UTC, J12934 commented on routes/dataErasure.js
> +        res.render('dataErasure', { e: email, q: q })
Would prefer to have the parameters be explicitly named `email` and `securityQuestion`.

2021-03-01 18:16 UTC, J12934 commented on routes/dataErasure.js
> +  const loggedInUser = insecurity.authenticatedUsers.get(req.cookies.token)
Is it intended that the securityQuestion is not acutally checked?

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +            window.location.href =  "http://localhost:3000/"
Hardcoded domain to `localhost`

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +  {{#if email}}
This is pretty confusing. Took me quite a while to get that this page gets reused on both the "dataerasure" and the "goodby" page. Might be nicer to have these be seperate templates.

Or at least have the parameter be named differently than `email` as this doesn't really have anything to do with how it is used.

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +					    },
Okay this is just confusing to me.
Why does the form gets submitted via ajax when the response is then used to replace the entire document.
This looks like it forcefully reimplements form requests.

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +    <script type="text/javascript">
The indention & formatting is this code is pretty weird 😕

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +                let button1 = document.querySelector("button");
The naming of these variables are pretty confusing

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +        document.cookie = 'token' + "=" + "" + ";Domain=localhost;path=/;" + expires;
Might be easier to do this with jquery, or provide some comment on what this is doing.

```js
// delete token cookie
$.cookie("token", null, { path: '/' });
```

2021-03-01 18:16 UTC, J12934 commented on routes/dataErasure.js
> +  res.render('dataErasure', profile)
This code is buggy.
The res status from line 202 is never acutally returned as the requests has already has a response, the rendered html from line 51. When the `models.PrivacyRequest.create` completes the requests is already done.

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +		<div class="mt-4 flex justify-end">
The inputs and buttons don't use the proper material design classes.
See the profile page for reference

2021-03-01 18:16 UTC, J12934 commented on views/dataErasure.hbs
> +		<div class="mt-4 flex justify-end">
Also inputs should ideally be properly label for accessibility.

2021-03-01 18:24 UTC, J12934 commented
Took the liberty to rename the PR to match it's content. Would be nearly impossible to find this again with its vague name.

2021-03-01 19:00 UTC, cigar-galaxy82 commented on routes/dataErasure.js
> +  const loggedInUser = insecurity.authenticatedUsers.get(req.cookies.token)
Now 

https://user-images.githubusercontent.com/56212958/109545125-72195500-7aee-11eb-8ff0-2e42eec253df.mp4

when the user goes to the page in the input block the placeholders are his email and the securityQuestion so this will make sure that user only sees his details. Earlier it never checked weather is logged in or not and when he types his email the security question he choose was send and answer to that was also not checked.

2021-03-01 19:11 UTC, cigar-galaxy82 commented on views/dataErasure.hbs
> +		<div class="mt-4 flex justify-end">
like using label tag?

2021-03-01 19:18 UTC, cigar-galaxy82 commented
@J12934 
will start make the changes required. Thank you for reviewing

2021-03-01 19:39 UTC, J12934 commented on routes/dataErasure.js
> +  const loggedInUser = insecurity.authenticatedUsers.get(req.cookies.token)
😕
None of that actually ensures that the answer entered to the security question is actually correct...
I can put anything in there and the deletion request gets created.

2021-03-01 19:48 UTC, cigar-galaxy82 commented on routes/dataErasure.js
> +  const loggedInUser = insecurity.authenticatedUsers.get(req.cookies.token)
It was also not ensured in the earlier version the dataErasure.

2021-03-01 19:55 UTC, J12934 commented on routes/dataErasure.js
> +  const loggedInUser = insecurity.authenticatedUsers.get(req.cookies.token)
Ah ok, wasn't aware of that.
@bkimminich was that intentional? Does anything depend on that not being checked?

2021-03-01 20:02 UTC, bkimminich commented
And please _take your time_ with the changes and local testing before submitting... 😉

2021-03-02 19:29 UTC, cigar-galaxy82 commented on views/dataErasure.hbs
> +		<div class="mt-4 flex justify-end">
Hi @J12934 I was able to use material design classes for button but they are messing with the javascript logic used to prevent submitting the button if form inputs are empty.

2021-03-03 00:08 UTC, cigar-galaxy82 commented on views/dataErasure.hbs
> +		<div class="mt-4 flex justify-end">
![Screenshot (330)](https://user-images.githubusercontent.com/56212958/109732160-a0785c80-7be2-11eb-80a5-4a7c3ab651a4.png)
Is this ok?

2021-03-04 02:42 UTC, cigar-galaxy82 commented on views/dataErasure.hbs
> +					    },
I used this way to make it similar to the one that was used to implement the challenge by captainFreak code. I can change this to use axios like I did earlier

2021-03-04 14:06 UTC, J12934 commented on views/dataErasure.hbs
> +		<div class="mt-4 flex justify-end">
Yup that look more like proper material design 👍

2021-03-04 15:15 UTC, cigar-galaxy82 commented
1.Deleting cookies using jquery
2.removed use of localhost:3000
3.used proper variable names
4.labeled inputs 
5.Now using proper material design
6.Added authentication so email entered is same as the one from the cookie
7.Proper indentation implemented

The e2e test failed because this version of ChromeDriver only supports Chrome version 89

2021-03-09 20:13 UTC, J12934 commented on views/dataErasure.hbs
> +                let button1 = document.querySelector("button");
Formatting, especially of the js code is still weird.

2021-03-09 20:29 UTC, J12934 requested changes
Can you please go over the comments in the review again?
I tried to mark the resolved one as resolved, but there are still many unaddressed comments :(

Especially https://github.com/bkimminich/juice-shop/pull/1593#discussion_r584926169 as it could significantly reduce the amount of logic required.

2021-03-09 20:29 UTC, J12934 commented on routes/dataErasure.js
> +  if (loggedInUser && loggedInUser.data.email === Email.email) {
This var naming is confusing.
Email is an object which has a key `email`?

2021-03-09 20:29 UTC, J12934 commented on routes/dataErasure.js
> +    res.render('dataErasure', Email)
The response is send even before the `models.PrivacyRequest.create` promise can resolve / reject.
This means the frontend would get a success response even if the Privacy request wasn't properly created.

2021-03-09 20:29 UTC, J12934 commented on routes/dataErasure.js
> +        res.render('dataErasure', { Email: email, securityQuestion: question.dataValues.question })
Uppercased `Email` is inconsistent with the variable naming scheme used in the codebase.

2021-03-09 20:59 UTC, cigar-galaxy82 commented on routes/dataErasure.js
> +  if (loggedInUser && loggedInUser.data.email === Email.email) {
Email is the object that contain values entered in the input block like email and answer

2021-03-09 21:10 UTC, cigar-galaxy82 commented on routes/dataErasure.js
> +    res.render('dataErasure', Email)
Using res.render would be better in the then block so it will only render html if property is created

2021-03-09 22:15 UTC, J12934 commented on routes/dataErasure.js
> +  if (loggedInUser && loggedInUser.data.email === Email.email) {
Yes I got that. But the variable name does not indicate what it actually is. It not just a email...

2021-03-09 22:51 UTC, cigar-galaxy82 commented on routes/dataErasure.js
> +  if (loggedInUser && loggedInUser.data.email === Email.email) {
ok I will remove the the use of the variable because it was used to compare only

2021-03-11 06:30 UTC, cigar-galaxy82 commented
![Screenshot from 2021-03-11 11-47-31](https://user-images.githubusercontent.com/56212958/110745444-45d5a500-8261-11eb-9540-8b72e598e84d.png)
Implemented challenge

2021-03-13 10:10 UTC, bkimminich commented
Hi @cigar-galaxy82, I don't understand the meaning of the screenshot you posted above in combination with the "Implemented challenge" comment. I don't see any challenge checks, also no changes to `challenges.yml`. So, I guess you meant "changes" referring to the review requests by @J12934?

2021-03-13 10:52 UTC, cigar-galaxy82 commented
I meant to say I was able to perform Local File Read on the new dataerasure component

2021-03-17 08:10 UTC, bkimminich commented
JFYI, as @J12934 did the code quality review and there were several unaddressed remarks over several iterations, I'll wait for his final assessment of the PR before we decide how to proceed with it. Thanks for your patience!

2021-03-17 13:58 UTC, cigar-galaxy82 commented
Ok :) 
This is the first time  I have created  PR with these many changes so there might still be lot of discrepancies. So, if the code is lacking  in anyway please do tell, because I want  to match my code to the level of juice-shop repo. Till then, I will continue working on ways to optimize score-board and will improve how I code so there will be less issues next time.

2021-03-18 20:06 UTC, J12934 commented
Most of the small remarks seem to be resolved, there are still two mayor comments open.
I marked them as resolved in GitHub.

https://github.com/bkimminich/juice-shop/pull/1593#discussion_r584926169
https://github.com/bkimminich/juice-shop/pull/1593#discussion_r584929346

These could really make this code a lot simpler. broken down I'd suggest to do the following:

1. Replace the client side java script and submit the fields using plain html / http forms. This fits better with the "server rendered" theme and would get of the client side js code. The backend would need to handle form data instead of the json body. This should not interfere with the hbs vulnerability.
2. Break up the template into two. The first one to render the form, the second one to render the result / success box which gets returned when the form is submitted. This would be the place where the unhandled user input (`req.body`) gets handed to `hbs`. This would get rid of the big confusing `if` block in the current template.

The PR also currently doesn't remove the presvious server side `erasureRequest.js` implementation, is this intended? Is it used in another place?

2021-03-19 19:29 UTC, cigar-galaxy82 commented
1.removed use of ajax and used html forms
2.divided template into two
3.didn't remove erasureRequest.js because it was falling some test cases

2021-03-21 14:20 UTC, cigar-galaxy82 commented
I will change the js files to typescript them open new PR

2021-03-21 14:20 UTC, closed without merging

2021-03-21 14:43 UTC, J12934 commented
You don't need to open a new pr to do that

2021-03-21 14:46 UTC, cigar-galaxy82 commented
but if I don't then there will be many conflict I think

2021-03-21 14:53 UTC, J12934 commented
You can merge the develop branch back in to your branch, or rebase it and force push. Neither requires opening a new pull request

2021-03-21 14:59 UTC, cigar-galaxy82 commented
Ok I can also do this.

2021-03-21 15:45 UTC, cigar-galaxy82 commented
I have created a new branch and made all the required changes but since I closed this PR I have to create a new now

2021-03-21 16:05 UTC, cigar-galaxy82 commented
I tried to do this but there where many error while running I think I should start from the beginning

2021-03-21 16:54 UTC, J12934 commented
Even when "strating from the beginning" you can keep the pr by force pushing the new changes to the branch.

2021-03-21 17:02 UTC, cigar-galaxy82 commented
Ok I will do that

2021-03-21 18:44 UTC, bkimminich commented
And _please_ make sure the code quality in the PR doesn't let it end in another tiresome review cycle, because we will do some significant codebase changes in the backend as we're now gradually moving it to TypeScript. Thanks!

2021-03-21 18:53 UTC, cigar-galaxy82 commented
I will make sure of that won't let it end like this some