Added the exifForBlueprintChallenge property and its tests
juice-shop/juice-shop pull request #1614
Opened 2021-04-02 13:30 UTC by the-pro

Resolves #1613 

Added a property `exifForBlueprintChallenge`
Added a test for the presence of this property in the image
Added a test to check its presence

2021-04-02 14:33 UTC, bkimminich requested changes

2021-04-02 14:33 UTC, bkimminich commented on config/default.yml
> +    exifForBlueprintChallenge: OpenSCAD
I suppose this is too simple. We can't assume that everyone will use the "Make" property in their EXIF data, so we'll have to make this part of the config. Like:

```
exifForBlueprintChallenge:
  Make: OpenSCAD
```

2021-04-02 14:33 UTC, bkimminich commented on lib/startup/validateConfig.js
> +    if (product.image === '3d_keychain.jpg') {
This can't be hard coded, as we don't know the name of the product image file for every custom config. You can use the `7ms.yml` config to test if your solution works with the non-default. There I used different blueprint file and different config (but I have no control over any EXIF data unfortunately as the file is downloaded from Internet). I hope it clarifies how this challenge could be configured, though.

See https://github.com/bkimminich/juice-shop/blob/master/config/7ms.yml#L87-L88

2021-04-02 14:33 UTC, bkimminich commented on test/server/configExifSpec.js
> +        if (product.image === '3d_keychain.jpg') {
Same as mentioned above.

2021-04-02 14:33 UTC, bkimminich commented on test/server/configExifSpec.js
> +              expect(1).to.equal(0)
Ouch... :-) ... I get what you're doing, but `expect.fail("Could not read EXIF data ...")` should be better.

2021-04-02 15:13 UTC, the-pro commented on lib/startup/validateConfig.js
> +    if (product.image === '3d_keychain.jpg') {
Could we check some other info for example the presence of `fileForRetriveBlueprintChallenge`

2021-04-02 15:16 UTC, the-pro commented on config/default.yml
> +    exifForBlueprintChallenge: OpenSCAD
So we have to check for the presence of every property of `exifForBlueprintChallenge` in the exif data

2021-04-02 17:54 UTC, the-pro commented
I did some changes as you mentioned

2021-04-03 04:36 UTC, chinggg reviewed
As for the circumstance of product.image being URL, is it correct to just use URL as the argument of ExifImage? Since I found the exif may only accept images present in a file system or buffer. (see https://github.com/gomfunkel/node-exif/blob/master/lib/exif/ExifImage.js#L18 and gomfunkel/node-exif#66)

2021-04-03 05:01 UTC, chinggg commented on lib/startup/validateConfig.js
> +    if (product.image === '3d_keychain.jpg') {
I have used the `7ms.yml` config to test if image from URL could be read, and it failed to pass the test. :cry:

2021-04-03 05:06 UTC, chinggg commented on test/server/configExifSpec.js
> +          ExifImage({ image: path.resolve(pathToImage) }, function (error, exifData) {
I think this may not work when `product.image` is a URL.
- `path.resolve(pathToImage)` will concatenate the working directory and the URL
- `ExifImage` may not accept the `image` argument except for a filesystem path or a buffer

2021-04-03 06:03 UTC, the-pro commented on test/server/configExifSpec.js
> +          ExifImage({ image: path.resolve(pathToImage) }, function (error, exifData) {
Oh i was testing the code you wrote in typescript for it. I guess i forgot to remove the `path.resolve()` 😅

2021-04-03 06:05 UTC, the-pro commented
Hm ... I guess we could download the file temporarily in the file system to check. what do you think @chinggg

2021-04-03 06:25 UTC, chinggg commented
> Hm ... I guess we could download the file temporarily in the file system to check. what do you think @chinggg
Great! We have two choices, one is to download the URL to buffer, another is to save the image to locall machine. I prefer the image to be saved to `pathToImage` since it may be used again (though the `product.image` will still be URL :smile: )
I have just made a new commit.

2021-04-03 06:28 UTC, bkimminich commented
Good idea. For reusability the path-to-image would need to be in the frontend/dist/frontend/... folder where the images are downloaded to in datacreator.ts.

2021-04-03 06:41 UTC, bkimminich commented
The YAML schema validation doesn't work like expected, it would complain about any config that does not use `Make` as the EXIF property. We might just use an array of strings and check if all of them appear in _any_ of the EXIF properties?

2021-04-03 06:43 UTC, chinggg commented
> Good idea. For reusability the path-to-image would need to be in the frontend/dist/frontend/... folder where the images are downloaded to in datacreator.ts.

I am not sure whether I should just add `frontend/dist` before `pathToImage` for all situations? If `product.image` is a filename, will it always exist in `frontend/dist/...`? Since I am modifying the test scripts, I wonder whether this path have the files I need.

2021-04-03 07:33 UTC, the-pro commented
> The YAML schema validation doesn't work like expected, it would complain about any config that does not use `Make` as the EXIF property. We might just use an array of strings and check if all of them appear in _any_ of the EXIF properties?

Sir could you tell how to define the schema for it as i am getting some errors

2021-04-03 08:03 UTC, bkimminich commented
```
exifForBlueprintChallenge:
  -
    type: string
```

Should allow to have a list of strings defined under that property.

2021-04-03 08:32 UTC, bkimminich commented
Can you agree on one of the two PRs for the basis of review/fixes? I'm starting to get confused where to look... :-D

2021-04-03 09:13 UTC, the-pro commented
> Can you agree on one of the two PRs for the basis of review/fixes? I'm starting to get confused where to look... :-D

I have lesser previous contributions i guess 😅

2021-04-03 09:22 UTC, bkimminich commented
I don't count commits to decide for GSoC students, trust me... 🤪

2021-04-03 10:06 UTC, chinggg commented on test/server/configExifSpec.js
> +describe('forBlueprintChallenge', () => {
I made another PR just because I found this PR hasn't migrated to TypeScript :zany_face:
@the-pro really does a lot work on this. I just made some extra modifications.
Like there, I suppose the first `describe` to have `configExif`, which is part of its filename, as its first argument because other files `test/server` all have this pattern.

2021-04-03 10:06 UTC, chinggg commented on test/server/configExifSpec.js
> +            pathToImage = pathToImage + product.image
And there I think @bkimminich actually want us to save the image to `frontend/dist/frontend/assets/public/images/products` for reusablity, not just `frontend/dist/frontend`

2021-04-03 10:11 UTC, the-pro commented on test/server/configExifSpec.js
> +            pathToImage = pathToImage + product.image
Thanks for that 

> And there I think @bkimminich actually want us to save the image to `frontend/dist/frontend/assets/public/images/products` for reusablity, not just `frontend/dist/frontend`

Oh my bad! thanks for reviewing it.

2021-04-03 10:16 UTC, chinggg commented on test/server/configExifSpec.js
> +            pathToImage = pathToImage + product.image
Thanks for replying. I also suggest to use `path.resolve()` instead of string operations to avoid errors. :smile:

2021-04-05 18:50 UTC, bkimminich commented
Closing this to avoid confusion across PRs. Please commit into #1615 if needed. Thanks!

2021-04-05 18:50 UTC, closed without merging