added code to check if lfr is performed
juice-shop/juice-shop pull request #1616
Opened 2021-04-04 09:26 UTC by cigar-galaxy82

2021-04-06 16:48 UTC, J12934 requested changes

2021-04-06 16:48 UTC, J12934 commented on routes/dataErasure.ts
> +            const sendlfrResponse: string = JSON.stringify(html).slice(0, 100) + '......'
Why is the html JSON.stringified?
The html is already a string. Calling `JSON.stringify` on it just wraps it as a JSON Document containing a single string.

2021-04-06 16:48 UTC, J12934 commented on routes/dataErasure.ts
>        const conditions: boolean = (req.body.layout.includes('ftp') || req.body.layout.includes('ctf.key') || req.body.layout.includes('encryptionkeys'))
This check might be vulnerable to path traversal type attacks.
The layout key should be expanded before running string comparisons against it to ensure that an attacker can't find a way to sneak around the comparisons using some weird char encoding. Not sure if this is actually possible but would't want to risk it, unless it's part of a challenge 😄

See OWASP Path Traversal Cheat Sheet: https://owasp.org/www-community/attacks/Path_Traversal

2021-04-06 16:48 UTC, J12934 commented on routes/dataErasure.ts
>            if (html === undefined) {
Should also check if either the `error` is defined or the `html` is `undefined`

2021-04-06 16:48 UTC, J12934 commented on routes/dataErasure.ts
>      res.clearCookie('token')
`res.clearCookie('token')` should probably be moved up.

clearCookie needs to be called before the response is send out. This happens to be the case because of a weirdness in res.render and the execution order of the code in the callback, but might confuse coders in the future. Probably best to move it before all of the if statements.

2021-04-06 16:48 UTC, J12934 commented on routes/dataErasure.ts
> +    if (req.body.layout !== undefined) {
I think we should add `layout` as a optional property on the `DataErasureRequestParams` interface, so that typescript doesn't get confused why we are accessing it.

```ts
interface DataErasureRequestParams {
  email: string
  securityAnswer: string
  layout?: string
}
```

2021-04-07 11:27 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
> +    if (req.body.layout !== undefined) {
I have placed layout keyword on top because using the spread operator it starts to expand object from email because of this I was not able to perform LFR using insomnia

2021-04-07 11:28 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
>      res.clearCookie('token')
resolved

2021-04-07 11:29 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
>            if (html === undefined) {
Now checks for it if html is undefined or error is defined

2021-04-07 11:49 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
>        const conditions: boolean = (req.body.layout.includes('ftp') || req.body.layout.includes('ctf.key') || req.body.layout.includes('encryptionkeys'))
I tried to access restricted files using some different encoding they didn't work the only way this check failed was by using capital letter so solve this I used toLowerCase()

2021-04-07 12:31 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
> +            const sendlfrResponse: string = JSON.stringify(html).slice(0, 100) + '......'
removed JSON.stringify

2021-04-08 14:19 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
> +    if (req.body.layout !== undefined) {
My mistake I misguided this based on some observations that I thought were correct won't happen again

2021-04-11 20:27 UTC, J12934 commented on routes/dataErasure.ts
> +    if (req.body.layout !== undefined) {
Can you mark the layout as optional? See code snippet in the original comment.
This makes it clear that it isn't always set.

2021-04-11 20:41 UTC, J12934 commented on routes/dataErasure.ts
>        const conditions: boolean = (req.body.layout.includes('ftp') || req.body.layout.includes('ctf.key') || req.body.layout.includes('encryptionkeys'))
Ok cool.
Just to be sure can be run the layout parameter though `path.resolve` to make sure that we are not missing any weird cases? Probably worth to store the lower cased and `path.resolve`d string to keep the checks more readable.

Also `conditions` could be better named to indicate what the conditions actually are. I'd suggest something like: `isForbiddenFile`.

2021-04-11 20:43 UTC, J12934 commented on views/dataErasureForm.hbs
> +    <div class="formBlock">
This change breaks the styling of the page :(
Did you maybe forget to commit changes to the css file?

2021-04-11 20:50 UTC, cigar-galaxy82 commented on views/dataErasureForm.hbs
> +    <div class="formBlock">
I guess I did will commit the changes next time this is how it looks
![Screenshot (432)](https://user-images.githubusercontent.com/56212958/114320847-975da200-9b35-11eb-856d-56c20c87377c.png)

2021-04-12 01:18 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
>        const conditions: boolean = (req.body.layout.includes('ftp') || req.body.layout.includes('ctf.key') || req.body.layout.includes('encryptionkeys'))
const filePath: string = path.resolve(req.body.layout).toLowerCase() 

This is Ok?

2021-04-20 17:33 UTC, bkimminich commented
I am at a loss deciding what to do with this PR, @cigar-galaxy82 and @J12934. What is it actually planning to achieve? Is it a stepping stone to the actual LFR challenge? Wouldn't it be possible to build the actual LFR challenge in without an intermediate PR? Please help me understand how to proceed with this. Thanks!

2021-04-20 18:08 UTC, cigar-galaxy82 commented
I am almost done with the e2e test, if @J12934 thinks all the previous checks to see if it is performed then I can push the e2e test so LFR challenge will be finish and ready to be exploited by the user

2021-04-20 20:01 UTC, bkimminich commented
In the meantime I've changed the wording and categorization for the challege itself a bit, see https://github.com/bkimminich/juice-shop/issues/1576#issuecomment-823471918.

2021-04-20 20:13 UTC, J12934 commented
Ah sorry missed that the changes were made.
Would be awesome if you could next time do:

- mark all review comment as resolved 
- press the "re-request review" button

Otherwise it's hard to keep track of github notification.

Agreed to include the challenge in this PR 👍

2021-04-21 17:40 UTC, J12934 commented
Is this PR really ready to review @cigar-galaxy82 ? Glanced over it and saw fixme comments, and the tests are failing.

2021-04-21 18:10 UTC, cigar-galaxy82 commented
1.I will remove the comment 
2.npm run protractor
   npm run lint
   npm run frisby 
passes

2021-04-21 18:21 UTC, bkimminich commented
`npm test` fails as you didn't add a country mapping for the new challenge for FBCTF.

2021-04-21 18:23 UTC, cigar-galaxy82 commented
Ok  I will add that

2021-04-21 18:39 UTC, cigar-galaxy82 commented
> `npm test` fails as you didn't add a country mapping for the new challenge for FBCTF.

Why are these challenges mapped with a country ?

2021-04-21 19:10 UTC, bkimminich commented
It's for FBCTF, see https://pwning.owasp-juice.shop/part1/customization.html#countrymapping-sub-mapping

2021-04-23 06:45 UTC, bkimminich commented on routes/dataErasure.ts
> +            next(new Error('No Such file exist'))
Isn't this a bit too artificial? Maybe I understand it wrong, but this code section is entirely for challenge verification. It shouldn't return any functional error message as if file access was intended and it just didn't find the file. What would happen if we let this one run through and just not perform the HTML slicing?

2021-04-23 07:07 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
> +            next(new Error('No Such file exist'))
If we don't use slicing then the whole contents of the file will be rendered which will make other challenges vulnerable

2021-04-23 08:33 UTC, bkimminich commented on routes/dataErasure.ts
> +            next(new Error('No Such file exist'))
That wasn't my point. The slicing is right, but the "File not found" error message feels arbitrary.

2021-04-23 09:10 UTC, cigar-galaxy82 commented on routes/dataErasure.ts
> +            next(new Error('No Such file exist'))
ok we can use the error emitted like **new Error(error)**

2021-04-25 11:56 UTC, bkimminich commented
Just played with it locally, and I think that letting the HBS error message just "bubble up" to the user is much more realistic for this vulnerability. I'd be interested in the opinion of @CaptainFreak and @J12934 before merging, though, as they had the original challenge idea and did 90% of the review of the implementation so far.

![image](https://user-images.githubusercontent.com/3531020/115992435-0d4e1880-a5ce-11eb-854d-abbdc84e2d38.png)

2021-04-27 17:11 UTC, J12934 commented
Yup, returning the original error message feels more like JuiceShop 😄

2021-04-28 05:23 UTC, merged