Gitpod config file for opening the project in gitpod.io
juice-shop/juice-shop pull request #1849
Opened 2022-07-25 06:32 UTC by knut-erik

Signed-off-by: knut-erik <kneh@equinor.com>

### Description

Added `.gitpod.yml` file for using gitpod.io for development and testing the project.
To test this you need to have an account at gitpod.io, and use the following url : 
`https://gitpod.io/#https://github.com/juice-shop/juice-shop/` to start the dev environment.

### Affirmation

- [X ] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

2022-07-25 21:33 UTC, bkimminich commented
Just tried this out, and it is indeed really neat! 👍 ... The install documentation is not that precise, though. I'll leave some inline comments.

2022-07-25 21:45 UTC, bkimminich requested changes

2022-07-25 21:45 UTC, bkimminich commented on .gitpod.yml
> +    command: npm run start
`npm start` is sufficient

2022-07-25 21:45 UTC, bkimminich commented on .gitpod.yml
> +    description: The main application web server
There is no other server needed, so why not just go with "The Juice Shop web server"?

2022-07-25 21:45 UTC, bkimminich commented on .gitpod.yml
> +  - name: Juice-Shop App
"OWASP Juice Shop" Or "Juice Shop Web Application" maybe?

2022-07-25 21:45 UTC, bkimminich commented on README.md
> +1. Login to [gitpod.io](https://gitpod.io) and use this [link](https://gitpod.io/#https://github.com/juice-shop/juice-shop/) to start a new workspace
Rather print out the URL (`<https://gitpod.io/#https://github.com/juice-shop/juice-shop/>`) instead of doing the "here" thing. Also might add a note that in order to deploy a fork the URL can be changed and it will launch that?

2022-07-25 21:45 UTC, bkimminich commented on README.md
> +2. After the Gitpod workspace is loaded, the environment installs (`npm install` is triggered by the `.gitpod.yml`)
For me Gitpod showed "Running" state very quickly but that is only the workspace, not the command to install & launch Juice Shop, which was still in progress and only after done the preview window appeared. This should be phrased a bit more clear that "Workspace running" does not equal "Juice Shop running".

2022-07-25 21:45 UTC, bkimminich commented on README.md
> +3. The juice-shop is now running and a preview window is launched. It is also available at `http://<EXTERNAL_WORKSPACE_IP>:3000`
The URL did not involve any IP and also no port for me when using "Open in Browser" option of Gitpod at least:

![image](https://user-images.githubusercontent.com/3531020/180878743-e4c257d4-b111-4829-a8e1-e20f0ad12239.png)
![image](https://user-images.githubusercontent.com/3531020/180878861-8225afe9-e8c3-4c24-b543-da3fb91d2d79.png)

When expanding the preview browser to its own tab, I rather ended up with

`3000-<GITPOD_WORKSPACE_ID>.<GITPOD_HOSTING_ZONE>.gitpod.io`

2022-07-25 21:53 UTC, bkimminich commented
One little question: It seems Gitpod is different from Heroku in the way it generates a URL which is not instantly publicly accessible, at least I could not access my own from an inconginto browser window (got a 401 error). Should we still consider disabling dangerous challenges by default similar to how we handle Heroku and Docker? We could use https://www.npmjs.com/package/is-gitpod to check this. Does that make sense to prevent someone from accidentally setting themselves up for being attacked? I'd rather be safe than sorry here, because I don't know how good Gitpod's access control is.

2022-07-25 21:56 UTC, bkimminich commented
> One little question: It seems Gitpod is different from Heroku in the way it generates a URL which is not instantly publicly accessible, at least I could not access my own from an inconginto browser window (got a 401 error). Should we still consider disabling dangerous challenges by default similar to how we handle Heroku and Docker? We could use https://www.npmjs.com/package/is-gitpod to check this. Does that make sense to prevent someone from accidentally setting themselves up for being attacked? I'd rather be safe than sorry here, because I don't know how good Gitpod's access control is.

This is what we'd have to extend, plus mapping an icon in the frontend on the Score Board and extending the description text etc.

https://github.com/juice-shop/juice-shop/blob/bd7e8f3c7af1a8f38ba4fa866000136cb472449a/lib/utils.ts#L153-L170

2022-07-26 06:32 UTC, knut-erik commented on .gitpod.yml
> +    command: npm run start
Tx!

2022-07-26 06:49 UTC, knut-erik commented on README.md
> +3. The juice-shop is now running and a preview window is launched. It is also available at `http://<EXTERNAL_WORKSPACE_IP>:3000`
True - the comment was not correct, as gitpod does not use ports in the format `:<portnr>`, but a workspace URL which is unique to the users workspace.

2022-07-26 06:55 UTC, knut-erik commented on README.md
> +2. After the Gitpod workspace is loaded, the environment installs (`npm install` is triggered by the `.gitpod.yml`)
Tried to update the description to be more inline with what really happens. Yes, the initial process and command in `.gitpod.yml` could still run when the workspace is launched. In other words, "Workspace running" != "Juice Shop running."

2022-07-26 07:04 UTC, knut-erik commented
> > One little question: It seems Gitpod is different from Heroku in the way it generates a URL which is not instantly publicly accessible, at least I could not access my own from an inconginto browser window (got a 401 error). Should we still consider disabling dangerous challenges by default similar to how we handle Heroku and Docker? 

True - the Gitpod url is not accessible publicly by default. The user needs to open the link to the public for the url to be accessible e.g. in a incognito window. If you click the ports in VS Code (bottom right corner), you will see options for ports, with a lock, which is clickable. [Example / screenshot <https://www.gitpod.io/docs/config-ports/#configure-port-visibility>. Regarding ports in general for Gitpod => <https://www.gitpod.io/docs/config-ports/>

> > Does that make sense to prevent someone from accidentally setting themselves up for being attacked?

Probably this make sense. I'm not that familiar with disabling dangerous challenges.

2022-07-26 08:03 UTC, knut-erik commented
@bkimminich FYI: Added changes to the `lib/utils.ts` file and `package.json` to check for Gitpod and disable dangerous challenges. Probably other places where Heroku and Docker is mentioned which needs changes? (Tooltip when hoovering over dangerous challenges)

2022-07-26 09:20 UTC, knut-erik commented
Question: I probably don't understand how you visually see that dangerous challenges are disabled running e.g. Docker. How is this marked in the e.g. score board for the user?

2022-07-27 06:59 UTC, knut-erik commented
How the score board looks when run with the `safetyOverride: true`using gitpod. Text includes gitpod.
![image](https://user-images.githubusercontent.com/3600521/181182233-64b5d971-3519-436b-9d4d-adf27032b4d2.png)

2022-07-29 23:25 UTC, bkimminich commented
🥳 Merging now! Thanks as lot, @knut-erik! If you'd like to receive some stickers as a thank-you, just mail or Slack-DM me your address!

2022-07-29 23:25 UTC, merged

2022-07-31 11:54 UTC, knut-erik commented
> 🥳 Merging now! Thanks as lot, @knut-erik! If you'd like to receive some stickers as a thank-you, just mail or Slack-DM me your address! 

Many thanks for the merge! Stickers are always welcome - will try to dm you in the OWASP slack.