Fixed Challenge to register an entirely blank user account
juice-shop/juice-shop pull request #1973
Opened 2023-02-17 11:56 UTC by Freedisch

### Description

. Checked if the request payload is sending empty data for user registration
. Trimmed leading/trailing spaces before sending to db
. A registration with `email: "   "` `password: "  "` `repeatPassword: "   "` will create `username:""` `password:""` with an empty email `email:""`
Resolved or fixed issue: #1958 

### Affirmation

- [x] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

2023-02-21 11:34 UTC, bkimminich commented
Overwriting the "Admin Registration" challenge wasn't [the idea described here](https://github.com/juice-shop/juice-shop/issues/1958#issuecomment-1398577256). This PR would make the "Admin Registration" challenge almost unsolvable, unless you coincidentally register an admin with and empty email/password.

If this is supposed to become an actual challenge, you need to create a new one in `challenges.yml` and then check for the empty email/password independently of any other challenges during registration.

2023-02-21 13:18 UTC, Freedisch commented
My bad, I misunderstood it. I will correct it

2023-02-26 10:56 UTC, bkimminich commented
The trimming needs to happen in the actual registration, either in a model hook or interception in the API endpoint, but definitely not in the verification of the challenge success. Otherwise it's not a real vulnerability, and also we can't make a coding challenge on top of this.

2023-02-26 15:32 UTC, Freedisch commented
So, I tried to trim the payload in the user registration endpoint but the issue is that I can only have access the email payload, but not the password or repeatPassword. 

![Screenshot_20230226_062833](https://user-images.githubusercontent.com/82499435/221420103-a8e6c839-e0a2-46ac-b02f-ce1da2d9edd8.png)

Here is the output of the `console.log(context.instance)`

![Screenshot_20230226_061801](https://user-images.githubusercontent.com/82499435/221419902-a41bdb78-9226-43c9-8233-03d4977d864a.png)

2023-02-26 16:26 UTC, bkimminich commented
The password is not returned to the client, that's intended behavior. But you can still access it from either the request or later the model (hashed).

2023-02-26 16:31 UTC, Freedisch commented
Alright 👍🏾

2023-02-27 13:49 UTC, Freedisch commented
The tests on my local machine works fine, but its fail during the CI/CD bcs the fbctf.yaml is "not active" due to the changes I made.

2023-02-27 14:45 UTC, bkimminich commented
I think your challenge is not in the https://github.com/juice-shop/juice-shop/blob/master/config.schema.yml yet, that's probably causing issues with the FBCTF config validation.

2023-02-28 09:49 UTC, Freedisch commented
What do you think about this new update? is everything okay with the way the email and the password are trimmed?

2023-03-13 06:24 UTC, bkimminich requested changes
There is currently nothing that prevents a user from simply creating a user with an empty string email and password _directly_, without letting the trim do this for him. A check needs to be added  - before the trimming - that the email and password length can't be 0. Then the challenge is only possible by using an email/password of blanks.

2023-03-13 06:24 UTC, bkimminich commented on server.ts
> +      if (req.body.email.trim().length === 0 && req.body.password.trim().length === 0) {
You check if a trim is required by trimming, and when it is, you do it again, otherwise not. This is less efficient than just trimming, because the outcome would be the same: Nothing happens if no trim is needed.

2023-03-13 06:24 UTC, bkimminich commented on config.schema.yml
> +      - uri:
Please do not mix code changes with formatting of existing code. Goes for the other lines similar as well.

2023-03-13 06:24 UTC, bkimminich commented on routes/verify.ts
> +  challengeUtils.solveIf(challenges.registerAdminChallenge, () => {
Please do not mix code changes with formatting of existing code.

2023-03-13 07:20 UTC, Freedisch commented on server.ts
> +      if (req.body.email.trim().length === 0 && req.body.password.trim().length === 0) {
I wanted to check if the payload was empty or not before trimming. But i got what you meant doesn't matter the payload the trim will still be apply if needed. I'm making the necessary changes.

2023-03-13 09:10 UTC, Freedisch commented
> There is currently nothing that prevents a user from simply creating a user with an empty string email and password _directly_, without letting the trim do this for him

I thought the idea was to trim all empty strings so that we could have only one entry in the database. If we are trimming only none empty string, it means we gonna multiple entries in the database for all the empty strings.

2023-03-13 22:07 UTC, bkimminich commented
I think the user model will prevent that with its unique constraint after the trimming in the express middleware.

But: This would all be easier to verify with some test cases, probably best on API level, e.g.

1. Username/password "" = Error b/c empty
2. Username/password " " = OK! -> Creates ""/"" user
3. Username/password "   " after 2. = Error from constraint
4. Username " horst " trimmed to "horst"
etc.

Also of course one Cypress test for the challenge exploit is also missing.

2023-03-14 20:23 UTC, Freedisch commented
> I think the user model will prevent that with its unique constraint after the trimming in the express middleware.
> 
> But: This would all be easier to verify with some test cases, probably best on API level, e.g.
> 
> 1. Username/password "" = Error b/c empty
> 2. Username/password " " = OK! -> Creates ""/"" user
> 3. Username/password "   " after 2. = Error from constraint
> 4. Username " horst " trimmed to "horst"
>    etc.
> 
> Also of course one Cypress test for the challenge exploit is also missing.

I guess we are good now. I added the condition for not allowing empty email/password for being created. 
I added the api test for the different used case u mentionned above except the one registering an empty user (when u register an empty email/password u get a bad request error, but the test I wrote it to expect a 400 error was failing and sending 201, I had to remove it). 
I added a cypress test for the challenge.

( I realized that there are some failling test for api bcs of a mismatch of expected status code, it is a normal behavior or should an issue be open for that )

2023-03-14 21:52 UTC, bkimminich commented
Very nice, CI/CD passed fine. API test running locally tend to sometimes do weird stuff. Not sure if it's timing/race condition issues, but if CI/CD passes, we're probably fine. I'll merge this into `develop` then will test it a bit locally and on Heroku Staging! 👍

2023-03-14 21:53 UTC, merged