TODO 1 /lib/antiCheat.ts
juice-shop/juice-shop pull request #1988
Opened 2023-03-28 02:06 UTC by sohamparate

### Description

TODO Consider coding challenges with identical/overlapping snippets as easier once one of them has been solved. 

### Approach 

For this, I created a 2D array of identical challenges and checked if the current challenge falls under this. If it does, check if other challenges in the same sub-array are solved; if yes, change the timeFactor to 0.  

### Affirmation

- [x] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

2023-03-28 04:48 UTC, bkimminich commented
The approach to manually maintain the overlapping coding challenges is not sustainable long term, as code refactoring etc. would let the array become outdated eventually. 

The overlap would have to be determined dynamically from the code or - more efficiently - by persisting this information while the RSN cache is created, e.g. using a dedicated cache file or extending the existing `cache.json` in a smart way - see https://pwning.owasp-juice.shop/appendix/code-snippets.html#refactoring-safety-net and https://github.com/juice-shop/juice-shop/tree/master/rsn.

2023-03-28 04:50 UTC, sohamparate commented
I understand, I'll try another approach and update this PR

2023-03-30 08:52 UTC, sohamparate commented
@bkimminich please check :)

2023-03-30 16:49 UTC, bkimminich commented on models/user.ts
> -const UserModelInit = (sequelize: Sequelize) => { // vuln-code-snippet start weakPasswordChallenge
Line break that is probably accidental?

2023-03-30 17:10 UTC, bkimminich commented
It's a good first approach, but it doesn't catch all cases of actual overlap. For example: `app.routing.ts` has this concrete situation:
```
// vuln-code-snippet start adminSectionChallenge scoreBoardChallenge
// vuln-code-snippet start tokenSaleChallenge
// vuln-code-snippet end adminSectionChallenge scoreBoardChallenge
// vuln-code-snippet end tokenSaleChallenge
```
where the expected outcome should be `[adminSectionChallenge, scoreBoardChallenge, tokenSaleChallenge]`.

Also thinkable would be a situation like
```
// vuln-code-snippet start A B
// vuln-code-snippet start C D
// vuln-code-snippet end C D
// vuln-code-snippet end A B
```
where the expected outcome should be `[A, B, C, D]`.

From looking at your code it would probably give back `[A, B]` and `[C, D]` in this example and in the real one from above `[adminSectionChallenge, scoreBoardChallenge]` (and `[tokenSaleChallenge]`?). So, it would miss some overlap.

I wouldn't go so far as to consider _how much_ overlap (by # lines) there is, but it should catch the mentioned cases.

2023-03-31 03:52 UTC, sohamparate commented on models/user.ts
> -const UserModelInit = (sequelize: Sequelize) => { // vuln-code-snippet start weakPasswordChallenge
It is intentional, the rest of the code has such comments in a separate line

2023-03-31 03:57 UTC, sohamparate commented
I only considered the code snippets' starting point to get the identical challenges array. I'll try to use the ending point as well and update this PR again :)

2023-03-31 09:52 UTC, sohamparate commented
Hello @bkimminich , I have come up with an approach that tracks the line number of the 'snippet start' and 'snippet end' of a particular challenge and checks if another challenge starts its own code snippet before the first one ends.

In my opinion, the best way to get the respective line numbers is to convert the file into a string array (using `content.split('\n')`) and perform regex search on that.

Using this approach, it can also be determined how much (in percentage) two of the challenges share the same code snippet. Although, I have a feeling that converting the contents of a file to an array of strings and then performing a lookup operation might have a higher computational cost. 

What do you think? Should I go ahead with this approach??

2023-03-31 10:16 UTC, bkimminich commented
> Hello @bkimminich , I have come up with an approach that tracks the line number of the 'snippet start' and 'snippet end' of a particular challenge and checks if another challenge starts its own code snippet before the first one ends.
> 
> In my opinion, the best way to get the respective line numbers is to convert the file into a string array (using `content.split('\n')`) and perform regex search on that.
> 
> Using this approach, it can also be determined how much (in percentage) two of the challenges share the same code snippet. Although, I have a feeling that converting the contents of a file to an array of strings and then performing a lookup operation might have a higher computational cost. 
> 
> What do you think? Should I go ahead with this approach??
> 
> 
> 

Love the idea, but this might really be something that needs pre-computation during CI/CD and then being accessed from a cache-file at runtime.

2023-03-31 10:55 UTC, sohamparate commented
I'm assuming that precomputation means that all of this will be computed only once before the website is loaded (or something similar). 
Tbh, I haven't touched that part (cache) of the code nor do I have much experience with how CI/CD works in general. So I think I'll learn these concepts first and come back again. 

Meanwhile, if I have some questions, I'll post them here (or on slack, if you prefer). Please keep this PR open, thanks :)

2023-03-31 11:11 UTC, bkimminich commented
> I'm assuming that precomputation means that all of this will be computed only once before the website is loaded (or something similar). 
> Tbh, I haven't touched that part (cache) of the code nor do I have much experience with how CI/CD works in general. So I think I'll learn these concepts first and come back again. 
> 
> Meanwhile, if I have some questions, I'll post them here (or on slack, if you prefer). Please keep this PR open, thanks :)

Calculating this once during startup similar to the the snippets themselves is probably easier and still fast enough. Maybe start with that, yes.

2023-04-01 08:10 UTC, sohamparate commented
Hey, can I add a new file `/lib/startup/identicalChallenges.ts` or something?

This file will run once at the startup and will be responsible to create an identical challenge array (only once during startup) and pass the file to /lib/antiCheat.ts for further computation.

2023-04-02 07:36 UTC, J12934 requested changes
Hi 👋
Thank you for taking the time resolving this todo 🙌

I just went through the code and noticed a couple of things which were off / could be improved, let me know if anything is unclear.

2023-04-02 07:36 UTC, J12934 commented on routes/vulnCodeSnippet.ts
> +  const identical2Darr: string[][] = []
What does `Darr` mean?

2023-04-02 07:36 UTC, J12934 commented on routes/vulnCodeSnippet.ts
> +  const identical2Darr: string[][] = []
Ahhh like 2D Array?

I'd call it identicalChallengeGroups top better represent what is acutally is instead of just describing the datatype.

Additionally i think the better type / datastructure here would be an array of sets as the strings in them have to be uniq allowing for easier checks later if the challenge is part of this identical group.



```suggestion
  const identicalChallengeGroups: Array<Set<string>> = []
```

2023-04-02 07:36 UTC, J12934 commented on routes/vulnCodeSnippet.ts
> +  return identical2Darr
Mh this is incorrect, if this is getting called a second time then `identical2Darr` is empty as the `cache.identicalChallenges` is set by then.
The variable `identical2Darr` should not exist at all but the value should be written directly to `cache.identicalChallenges` (or `cache.identicalChallengeGroups` when following the suggestion from above to rename)

2023-04-02 07:36 UTC, J12934 commented on lib/antiCheat.ts
> +      })
The entire "identical challenge detection" block here should probably be moved into its own function and not happen here in this function.

E.g. to make it clear what is getting checked here and what the acutal outcome is when an identical challenge has already been solved.
```suggestion
  if (wasIdenticalChallengeAlreadySolved(challenge)) {
    timeFactor = 0
  }
```

2023-04-02 07:36 UTC, J12934 commented on lib/antiCheat.ts
> +  })
Getting the index out doesn't seem to be required here as we primarly care about the group so we can just get it out directly.

```suggestion
  const identicalChallengeGroupForSolvedChallenge = identicalChallengeGroups.find(
    (identicalChallengeGroup) => identicalChallengeGroups.has(challenge.key)
  )
```

2023-04-02 08:22 UTC, sohamparate commented
> Hi 👋 Thank you for taking the time resolving this todo 🙌
> 
> I just went through the code and noticed a couple of things which were off / could be improved, let me know if anything is unclear.

Thanks for all the suggestions, I'll update it soon and will keep these in mind for future PRs 🙌

2023-04-02 09:12 UTC, closed without merging

2023-04-02 09:15 UTC, sohamparate commented
I messed up the git thingy... I'll create a new PR :')

2023-04-05 06:57 UTC, J12934 commented
@sohamparate did something go wrong with the new PR?
I don't see one yet :) Let me know if I can help in any way. (also no rush if you just have been busy :D)

2023-04-05 07:09 UTC, sohamparate commented
> @sohamparate did something go wrong with the new PR?
> I don't see one yet :) Let me know if I can help in any way. (also no rush if you just have been busy :D)

Yes it's almost ready and I'm looking on how to optimize it (since my approach uses a triple for loop🙂)
I'll create a draft PR later in the evening!!