Add a new Faucet and Honey Pot NFT Mint Challenge
juice-shop/juice-shop pull request #2050
Opened 2023-07-31 13:53 UTC by rishabhkeshan

### Description

Added the second Web3 challenge as part of GSoC'23, "Mint the Honey Pot"

- Added a new photo with redirection to /bee-faucet in the Photo Wall Challenge
- Added a new page with 3 sections:
    1. Metamask Wallet Connect
        - Added metamask wallet connect button to connect to the Sepolia chain with error handling and snack notifications
    2. Bee Faucet
        - Added a faucet container where user is invited to gather bees from the generous bee owner.
        - An input field with a submit button where users can extract a limited number of bees from the faucet, contract call initiated to the Faucet contract to extract BEE tokens from the same.
    3. Honey Pot NFT
        - Added a NFT mint section, where users can deposit 1000 BEE tokens and mint the NFT. 
        - The mint function interacts with the NFT contract deployed, withdraws 1000 tokens and mints the NFT to the user wallet
- Added ethers and Wagmi core library to initiate connection to metamask and talk to the blockchain.
- Added the required backend route for challenge solved check.

### Userflow

- User goes to the Photo Wall section of the Juice Shop to find an out of place photo looking like a NFT.
- He hovers over it to find a redirection url, clicks it and is directed to the /bee-faucet page.
- User sees a connect wallet, faucet and NFT mint section.
- - User needs to download or connect his metamask wallet and switch to the Sepolia chain to get started. They are prompted if they are connected to any other chain.
- He finds that he can mint a Honey Pot NFT by paying 1000 BEE tokens.
- The BEE tokens are extracted from the BEE faucet where there is a catch that the BEE balance in the faucet is always lesser than 256.
- Users need to find the trick to extract more money from the faucet than the faucet balance to mint the NFT and successfully complete the challenge.
- Appropriate error messages are shown if the user tries to enter a negative value or a value greater than 256 as the flaw lies in the fact that the contract stores the balance in a Uint8 value which can store a maximum value of 256 else it overflows or underflows and wraps to 0 or 255 respectively, in case the value exceeds.
- Users need to find this loophole, extract a minimum of 1000 tokens and mint the NFT to successfully complete the challenge.

### Affirmation

- [ ] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

2023-08-02 16:14 UTC, ShubhamPalriwala requested changes
Hey, just a quick higher level overview on the application level and here's my take:
- Instead of a toast when the user does not have funds, lets show the error/warning just below the text box like we do for input validation itself
- Lets not have the components below ie that make the page scrollabe so we need to redesign the page and put them into a normal height screen!/
- Move the "Connect to Metamask" button inside one of the components or somewhere on the right top

2023-08-03 18:04 UTC, J12934 requested changes

2023-08-03 18:04 UTC, J12934 commented on frontend/package.json
> +    "axios": "^1.4.0",
axios isn't used

2023-08-03 18:04 UTC, J12934 commented on frontend/package.json
> +    "ethers": "^5.7.2",
Adding ethers to the frontend bundle brings the already big frontend bundle from an already quite big `408.83 kB` to `536.67 kB` (compressed). (`2.33 MB => 2.80 MB` uncompressed)

This seems like quite a big increase for a challenge on a hidden page.
Is this is really required to have (the entire lib) on that page it would be good if the page could be moved to a seperate lazy loaded module: https://angular.io/guide/lazy-loading-ngmodules
Then this would at least not increase the size of the default bundle.

2023-08-03 18:04 UTC, J12934 commented on frontend/src/app/faucet/faucet.component.ts
> +        this.keysService.nftMinted().subscribe(
The easiest solution seems to be to look at the frontend code in the devtools and just trigger this endpoint?
Is there a way to verify this challenge in a way which can't be easily cheated?

2023-08-03 18:04 UTC, J12934 commented on frontend/src/app/photo-wall/photo-wall.component.html
> +                        <a *ngIf="twitterHandle && image.title"
This seems hacky, why is a photo on the photo wall with a twitter handle and a image title automatically the bee faucet image?
I'd suggest adding another attribute the the photo wall config as its done for the `geoStalkingMetaSecurityQuestion`

2023-08-03 18:04 UTC, J12934 commented on frontend/src/assets/public/ContractABIs.ts
> +export const nftABI = [
As a blockchain noob: What is that and do we write this ourself?

Or is this copied from somewhere and is "safe" for us to assume that it's correct?
I don't know how I'd verify if that works or not.

2023-08-03 18:04 UTC, J12934 commented on frontend/src/assets/public/ContractABIs.ts
> +export const nftABI = [
If this is something that we need to maintain, is there a way to write tests for this?

2023-08-03 18:04 UTC, J12934 commented on routes/nftMint.ts
> +module.exports.nftMintCheck = function nftMintCheck () {
Could be deleted. The frontend could then use either

1. the generic challenge api to check the challenge status: `GET /api/Challenges/?key=nftMintChallenge`
2. subscribing to the challenge solved websockets

2023-08-03 18:04 UTC, J12934 commented on frontend/src/app/faucet/faucet.component.html
> +  <div class="section-2">
section-2 is really nondescripive as a name

2023-08-03 18:04 UTC, J12934 commented on frontend/src/app/faucet/faucet.component.html
> +        <h1>The Enchanted Honey Pot</h1>
pages should not have more then one h1

2023-08-03 18:04 UTC, J12934 commented on frontend/src/app/faucet/faucet.component.html
> +<div class="header">
this sites mixes 3 different styling methods: inline styles, css classes and fx styling directives (which are deprecated)

Ideally only one would be used or at least one primarily and only using a different styling method when it is required for the situation.

2023-08-03 18:04 UTC, J12934 commented on frontend/src/app/faucet/faucet.component.ts
> +    window.ethereum.on('chainChanged', this.handleChainChanged.bind(this))
some of this code doesn't handle the absence of `window.ethereum` not nicely.
would be cool to always check this to ensure its there before accessing it.

(ideally having it structured in a way so that we have to do this check only once).

2023-08-04 01:57 UTC, rishabhkeshan commented on frontend/package.json
> +    "ethers": "^5.7.2",
Hey @J12934, the ethers library would be used for the other 2 challenges as well and is the standard js library for blockchain calls, do you suggest having all the 3 challenge pages as a lazy loaded module?

2023-08-04 01:59 UTC, rishabhkeshan commented on frontend/src/app/photo-wall/photo-wall.component.html
> +                        <a *ngIf="twitterHandle && image.title"
Had a discussion in our last meet, reverting the changes there to make it look same as the other photo cards.

2023-08-04 02:08 UTC, rishabhkeshan commented on frontend/src/assets/public/ContractABIs.ts
> +export const nftABI = [
Hey @J12934, ABIs are in short Human Readable binary codes generated by the Solidity Compiler which are necessary for accessing smart contract functions on the frontend to initialize and call the same.

More on ABIs from official Solidity docs: https://docs.soliditylang.org/en/v0.8.21/abi-spec.html

We can separately write internal tests for Smart Contracts though not for ABIs in particular, E2E testing of the frontend calls is possible through [Synpress(built on top of Cypress)](https://github.com/Synthetixio/synpress)

2023-08-04 04:15 UTC, rishabhkeshan commented on frontend/src/app/faucet/faucet.component.ts
> +    window.ethereum.on('chainChanged', this.handleChainChanged.bind(this))
I was initially calling the beeBalance functions on load, have now removed them and they only get called once user is authenticated via his wallet.
Also the session variable takes care of the rest hadnling for the withdraw and mint functions.

2023-08-04 05:06 UTC, rishabhkeshan commented on routes/nftMint.ts
> +module.exports.nftMintCheck = function nftMintCheck () {
Thanks, have changed the same the generic api call

2023-08-04 05:22 UTC, rishabhkeshan commented on frontend/src/app/faucet/faucet.component.ts
> +        this.keysService.nftMinted().subscribe(
One approach we could take is:
As soon as a user mints the NFT, we can pass the connected wallet address of the user to the backend, the backend will fetch all NFT holders and check if the current wallet address passed has the NFT, if yes, the challenge will be marked as solved.
Caveat: A person can pass the wallet address of another wallet which holds the NFT.


What do you think of this?

2023-08-07 20:08 UTC, J12934 commented on frontend/package.json
> +    "ethers": "^5.7.2",
yes, I'd put them all in one lazyly loaded module

2023-08-07 20:10 UTC, J12934 commented on frontend/src/app/faucet/faucet.component.ts
> +        this.keysService.nftMinted().subscribe(
Is there no way to actually check if that address belongs to the user?
Or the minted nft (whatever that means)?

2023-08-07 20:12 UTC, J12934 commented on frontend/src/assets/public/ContractABIs.ts
> +export const nftABI = [
So this is generated by/from something? Is that documented somewhere? If the underlying code changes how do we update this abi?

2023-08-07 22:30 UTC, bkimminich requested changes

2023-08-07 22:30 UTC, bkimminich commented on data/static/codefixes/adminSectionChallenge_1_correct.ts
> +    path: 'bee-faucet',
I think the component name is fine, but maybe we can switch the path and corresponding screen labels to `bee-hive` for an extra pun?

2023-08-07 22:30 UTC, bkimminich commented on data/static/challenges.yml
> +  hint: 'Extract more BEEs than the owner has.'
This hint is a bit too "on-the-nose".

2023-08-07 22:30 UTC, bkimminich commented on frontend/package.json
> +    "ethers": "^5.7.2",
Is it feasible to introduce lazy loading for a 130KB size increase or should we rather open a backlog issue to look into lazy loading in a more holistic way overall? Currently only our Hacking Instructor loads lazily, and that doesn't use Angular anyway.

2023-08-07 22:30 UTC, bkimminich commented on frontend/src/app/faucet/faucet.component.ts
> +        this.keysService.nftMinted().subscribe(
Can we verify that the actually connected wallet (assuming it must be owned by the user, otherwise they wouldn't have been able to connect it) holds the actual NFT?

I agree that we can't have any challenges that just rely on triggering some easy-to-spot endpoint. We do have some "secret" endpoints for challenges where it's about visiting a certain page (like Score Board, Admin Section, Token Sale) and those are verified by some pixel image being loaded from the backend. While this is of course also cheatable, when a user finds out about these images, it's bascially equivalent to having found the pages. For the NFT minting that is not the same.

2023-08-07 22:32 UTC, bkimminich commented on data/static/codefixes/adminSectionChallenge_1_correct.ts
> +    path: 'bee-faucet',
It was agreed to keep the bee-haven name, so this is not relevant any more.

2023-08-08 04:59 UTC, J12934 commented on frontend/package.json
> +    "ethers": "^5.7.2",
Yes we can create a backlog item for it.

I'd at least try to set it up right away to see if it really is too much work. Generally setting up lazy loading in angular isn't too hard if you properly put the components into separate modules

2023-08-08 09:00 UTC, rishabhkeshan commented on frontend/src/assets/public/ContractABIs.ts
> +export const nftABI = [
Yes this is generated from the contract, if the contract is updated, the same needs to be compiled again which in turn generates the ABI.
We are maintaining a separate repository for the contracts which has the compiled ABIs as well, will soon add a README for easier local setup
https://github.com/juice-shop/web3-contracts

2023-08-08 09:03 UTC, rishabhkeshan commented on frontend/package.json
> +    "ethers": "^5.7.2",
Alright I will try the same once and get back.

2023-08-08 10:59 UTC, rishabhkeshan commented on frontend/package.json
> +    "ethers": "^5.7.2",
Hey @J12934 I have implemented lazy loading and the frontend build is back to 409KB.
It would be great if you could have a look at the code for the faucet.module file, I have tested on my end and everything looks to be working fine.

![image](https://github.com/juice-shop/juice-shop/assets/58903797/d8bd1684-7137-405a-9f7a-623375dc87b5)

2023-08-08 11:39 UTC, rishabhkeshan commented on frontend/src/app/faucet/faucet.component.ts
> +        this.keysService.nftMinted().subscribe(
I think one ideal way to ensure the challenge cannot be cheatable is adding an event emitter to the contract. 

The backend will have a listener for the mint event emitted by the contract. If a NFT is minted, it will store the address of the minter in an in-memory array.
On the frontend, we will add a backend call after the NFT mint with the connected wallet address of the user(derived from metamask), if the wallet is there in the array, the challenge is shown as solved successful and the wallet address is removed from the backend array.

What do you think of this solution?

2023-08-08 14:50 UTC, J12934 commented on frontend/package.json
> +    "ethers": "^5.7.2",
Nice 😊

2023-08-08 19:00 UTC, rishabhkeshan commented on frontend/src/app/faucet/faucet.component.ts
> +        this.keysService.nftMinted().subscribe(
Hey @bkimminich @J12934 I have modified the code to integrate the above solution. Let me know if the logic seems fine.

I have added an event emitter on the contract as soon as a NFT is minted.

Now in the backend I have created an event listener route which is called on load of the faucet component.

![image](https://github.com/juice-shop/juice-shop/assets/58903797/57c58b94-c13f-439b-b320-010c0d1174c7)

In the above code, I am creating the event listener once and the `isEventListenerCreated` acts as a flag so that every time on page refresh a new Event Listener is not created.
Post that I am maintaining a in-memory set of `addressesMinted` which stores all wallet addresses that mint the NFT.


Now as soon as the NFT is minted on the frontend (with a set timeout of 3.5 seconds) post NFT mint confirmation to allow event polling, I pass the metamask wallet address of the user from the frontend to the backend.

![image](https://github.com/juice-shop/juice-shop/assets/58903797/fb0f395d-fd1e-44c2-a857-cb102ee4346c)

In the backend, the `walletNFTVerify` function checks whether the metamask address received from the frontend is part of the `addressesMinted` Set, if yes the particular address is removed from the set and the challenge is marked as solved.

![image](https://github.com/juice-shop/juice-shop/assets/58903797/311d0858-89f1-48e2-b32b-75c0a71a154f)

2023-08-08 19:18 UTC, rishabhkeshan commented on data/static/challenges.yml
> +  hint: 'Extract more BEEs than the owner has.'
Yes, I missed to change it, as we discussed the first hint is supposed to be hinting towards the user finding the photo wall, I was thinking of something like: "Discover NFT wonders among the captivating visual memories."

2023-08-14 10:07 UTC, merged