Develop
juice-shop/juice-shop pull request #2151
Opened 2023-11-23 14:50 UTC by bogminic

### Description
Keep direct links to challenges stable for OpenCRE and others issue #2149

Modify the scoreboard code to incorporate the following proposed solution:

1. If both ?challenge=<name> and ?searchQuery=<name> are query parameters, prioritize ?searchQuery=<name> and ignore ?challenge=<name>.
2. If only ?challenge=<name> is a query parameter (without ?searchQuery=<name>), convert ?challenge=<name> to ?searchQuery=<name> and locally trigger the route without a browser reload.

Additionally, should a test case be included?"

Resolved or fixed issue:  #2149

### Affirmation

- [x] My code follows the [CONTRIBUTING.md](https://github.com/juice-shop/juice-shop/blob/master/CONTRIBUTING.md) guidelines

2023-12-01 06:23 UTC, bkimminich commented
👋 Hi! Sorry for the delay, I was swamped with work this week. Will try your implementation locally this weekend and provide feedback.

2023-12-02 10:13 UTC, bkimminich requested changes

2023-12-02 10:13 UTC, bkimminich commented on frontend/src/app/score-board/score-board.component.spec.ts
> +    mockActivatedRoute = {
To set the route for *all test cases* here is not a good idea. Can this be done just locally in the test case itself?

2023-12-02 10:13 UTC, bkimminich commented on frontend/src/app/score-board/score-board.component.ts
> +  updateParamsForOpenCRE (queryParams): boolean {
Function name should more generically explain what is going on, like `rewriteLegacyChallengeDirectLink()` or `handleLegacyChallengeDirectLink()` maybe?

2023-12-02 10:13 UTC, bkimminich commented on frontend/src/app/score-board/score-board.component.ts
> +    if (queryParams.challenge && !queryParams.searchQuery) {
I think we might want to also handle the case where both are sent, and simply do nothing except logging a warning to the console that the "challenge=challengeName" parameter is deprecated and "searchQuery=challengeName" should be used instead. The same warning we should also log in the rewrite-case, of course.

2023-12-03 05:14 UTC, bogminic commented on frontend/src/app/score-board/score-board.component.spec.ts
> +    mockActivatedRoute = {
Moved the init part inside the test.

2023-12-03 05:15 UTC, bogminic commented on frontend/src/app/score-board/score-board.component.ts
> +  updateParamsForOpenCRE (queryParams): boolean {
Renamed function to rewriteLegacyChallengeDirectLink.

2023-12-03 05:18 UTC, bogminic commented on frontend/src/app/score-board/score-board.component.ts
> +    if (queryParams.challenge && !queryParams.searchQuery) {
I have logged the warning as you suggested. Please review the messages to ensure they are correct.

2023-12-03 18:55 UTC, bkimminich approved these changes

2023-12-03 18:55 UTC, merged

2023-12-03 18:57 UTC, bkimminich commented
🥳 Thanks for implementing this feature! If you send me a Slack DM or email with your post address, I'll make sure that some Juice Shop stickers find their way to you as a thank-you!