initial test suite for old xss
juice-shop/juice-shop pull request #567
Opened 2018-05-23 13:39 UTC by CaptainFreak

Tests are failing. Need feedback.

2018-05-23 14:52 UTC, J12934 requested changes

2018-05-23 14:52 UTC, J12934 commented on test/client/controllers/trackResultControllerSpec.js
> +  describe('TrackResultController', function () {
A lot of test are failing because the `TrackResultController` send out ajax requests when initialized.
They fail because you have not defined that you are actually expecting these requests.

2018-05-23 14:52 UTC, J12934 commented on test/client/controllers/trackResultControllerSpec.js
> +  describe('TrackResultController', function () {
This expectGet is missing in the 'should be defined' test.
The other two fail because the Controller is actually requesting  `/rest/track-order/undefined` because you dont specify the arguments the Controller should be initialized with. Take a look at the other tests (e.g. the ProductsDetailsController Spec on how to do this)

2018-05-23 14:52 UTC, J12934 commented on test/client/services/trackResultServiceSpec.js
> +  describe('TrackOrderService', function () {
Not directly a bug but the file appears to have the wrong name

2018-05-23 14:52 UTC, J12934 commented on test/client/services/trackResultServiceSpec.js
> +  describe('TrackOrderService', function () {
Or might actually corresponding to a bug i have no real idea how the dependency injection magic in these tests are working. (How does the Injection service know what to inject if never really specified?)

2018-05-23 15:39 UTC, CaptainFreak commented on test/client/controllers/trackResultControllerSpec.js
> +  describe('TrackResultController', function () {
``` it('should get tracking results with given id', inject(function () {
      $httpBackend.expectGET('/rest/track-order/5267-f9cd5882f54c75a3').respond(200, {data: {orderId: 'Test Juice'}})

      $httpBackend.flush()

      expect(scope.results).toBeDefined()
      expect(scope.results.orderId).toBe('Test Juice')
    })) ```

Is this not sufficient @J12934 ?

2018-05-23 15:40 UTC, shoebpate1 commented on test/client/services/trackResultServiceSpec.js
> +  describe('TrackOrderService', function () {
Actually TrackOrderService.js is the file which fires get request so isn't it correct ?

2018-05-23 15:44 UTC, J12934 commented on test/client/services/trackResultServiceSpec.js
> +  describe('TrackOrderService', function () {
The service is called TrackOrderSerivce but the test file is named testResultServiceSpec

2018-05-23 15:48 UTC, J12934 commented on test/client/controllers/trackResultControllerSpec.js
> +  describe('TrackResultController', function () {
It should be enought but the expectGet is missing in the 'should be defined' test.

The `$httpBackend.expectGET('/rest/track-order/5267-f9cd5882f54c75a3').respond(200, {data: {orderId: 'Test Juice'}})` line isnt really working because the controller never acutally calls  '/rest/track-order/5267-f9cd5882f54c75a3'  but '/rest/track-order/undefined' because the controller is missing the orderId attribute on the scope. you'll need to pass that into the controller in the beforeEach call.

2018-05-23 15:50 UTC, shoebpate1 commented on test/client/controllers/trackResultControllerSpec.js
> +  describe('TrackResultController', function () {
```beforeEach(inject(function ($rootScope, $controller) {
      scope = $rootScope.$new()
      controller = $controller('TrackResultController', {
        '$scope': scope,
        'id': '5267-f9cd5882f54c75a3'
      })
    }))```

Is this the way to add arguments to initialization?

2018-05-23 15:53 UTC, J12934 commented on test/client/services/trackResultServiceSpec.js
> +      expect(result).toBe('apiResponse')
The problem here is that result actually equals `{ data: 'apiResponse' }` not just `'apiResponse'`.
Otherwise the test seems to be working

2018-05-23 15:58 UTC, CaptainFreak commented on test/client/services/trackResultServiceSpec.js
> +  describe('TrackOrderService', function () {
so should it be be trackOrderServiceSpec.js ? It still fails.

2018-05-23 16:02 UTC, J12934 commented on test/client/services/trackResultServiceSpec.js
> +  describe('TrackOrderService', function () {
yup should be called trackOrderServiceSpec.
Sorry my second comment was wrong / missleading the name is not cause for the test failure.

2018-05-23 16:21 UTC, J12934 commented on test/client/controllers/trackResultControllerSpec.js
> +  describe('TrackResultController', function () {
I just noticed that the orderId doesnt get directly inserted into the TrackResultController as an argument but that it reads it from the $location service.
I think the best solution to do this is to mock the locations service so that it will return the value we expect. As a reference take a look at the basket controller spec which does a similar thing with $window. https://github.com/bkimminich/juice-shop/blob/06cfe881178144516f36fe0e4fa42d623b08e055/test/client/controllers/basketControllerSpec.js#L6

2018-05-25 16:36 UTC, bkimminich commented
I'll merge an see if I can fix them...

2018-05-25 16:36 UTC, merged

2018-05-25 17:20 UTC, bkimminich commented
Okay, I need to fiddle with it some more, but I think there actually is an unnecessary request happening... So the test assumption is right, but the implementation is somewhat wrong. Also naming is a bit odd with `save` for tracking orders?

2018-05-25 19:34 UTC, bkimminich commented
Oookay, no the test assumption is wrong... Flushing `$http` is okay, but you never actually defined the orderID, that would match your `expectedGET`. I'll fix and show you.

2018-05-25 20:18 UTC, bkimminich commented
In the `searchResultControllerSpec.js` it is the same issue, which I solved a bit cheesy by simply expecting `undefined` as the search value but still responding with something sensible. I did it the same way now in your tests, b/c that's the quickest fix for now.

Also, the test assumptions were a bit off what actually happens, so I removed on of the tests. See: 6a41c83

@CaptainFreak: Please pull the `develop` and send a new PR which renames the functions more appropriately. Better use `find` or `track` instead of `save`. Also I'd vote for consistency in naming it `orderId` or `orderNo`, not mixes of both.