Node module challenge
juice-shop/juice-shop pull request #611
Opened 2018-06-13 11:45 UTC by CaptainFreak

2018-06-13 21:56 UTC, J12934 commented
This looks really cool, very nice! 
I will try this out tomorrow 😀

2018-06-14 15:16 UTC, J12934 requested changes
Also i assumed that i would solve the upload type challenge by uploading the zip file.
But its not getting solved.

2018-06-14 15:16 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
This console.log gets trigger every time even when this is used in the regular not abusive way.

This is the error which gets logged:
```
{ Error: ENOENT: no such file or directory, open 'uploads/complaints/../../ftp/legal.md'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'uploads/complaints/../../ftp/legal.md' }
```

2018-06-14 15:16 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
If this error is never relevant, i guess we should not log it.

2018-06-14 15:18 UTC, J12934 commented
The challenge is really cool!
I created the zip archives with the tool you have send us and it worked like a charm 😉

2018-06-14 15:23 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Ohk so we just don't do anything with the error ?

2018-06-14 15:28 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
No wait, this error is actually valid.
The file was not really overwritten, but the challenge got solved

2018-06-14 15:28 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Is the `legal.md` file porerly overwritten on your machine @CaptainFreak ?

2018-06-14 15:35 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
It works. Can you use the zip file i created which is in tests/files and check.

2018-06-14 15:41 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
That also doesn't work on my machine

2018-06-14 15:44 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Actually it works smoothly for me. Always the above error is coming for you ?

2018-06-14 15:47 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Oh I forgot to tell .. The legal.md file in the archive is only differing in one character and that is an extra `s` in `##Terms of Use` . So u might have not been able to observe if any other error is not present.

2018-06-14 15:48 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
It become `Uses`

2018-06-14 15:54 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Mh no that also doesnt change.
I tried running it in docker and it also doesn't appear to be working in docker.
Can you build the container locally and test it with docker on your machine?

2018-06-14 16:15 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Oh am not that familiar with docker. So can I make container of my own fork ?

2018-06-14 16:17 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
What errors you are getting ?

2018-06-14 16:17 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
It the same error as above

2018-06-14 16:19 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
You can build and start the docker container like this (assuming you have docker installed):
```sh
docker build -t juice-shop-zip .
docker run -p 3000:3000 juice-shop-zip
```

2018-06-14 16:22 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Oh got it. So in my local branch I do have the requires folders ```uploads/complaints/``` but I did not knew that empty directories dont get commited !

2018-06-14 16:26 UTC, shoebpate1 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
So should we just add .gitignores to the directories ,So that they get committed ?

2018-06-14 16:28 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Personally prefer .gitkeep but not .gitignore would also work.
See: https://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep

2018-06-14 16:31 UTC, CaptainFreak commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Yea chose .gitkeep already :)

2018-06-14 16:36 UTC, J12934 commented on routes/fileUpload.js
> +                  entry.pipe(fs.createWriteStream('uploads/complaints/' + fileName).on('error', function (e) { console.log(e) }))
Okay very nice its now working properly!

2018-06-14 16:54 UTC, J12934 approved these changes

2018-06-14 18:13 UTC, merged