Hpp challenge
juice-shop/juice-shop pull request #623
Opened 2018-06-20 16:02 UTC by CaptainFreak

2018-06-21 08:52 UTC, J12934 requested changes
Okay very cool that you found a way to do this this fast! 👍

But there are some issues in this PR:
1. The Frontend doesn't appear to be using the new custom endpoint. The UI sends a `PUT` request which gets handled by the epilogue (which is still active and should be taken out). Your new endpoint listens on POST Requests.
2. Some parts of the codes are a bit hard to read. I added some inline comments for these parts with suggestion how to improve the readability.

Hit me up on slack if you got any questions (faster than doing it on github)

2018-06-21 08:52 UTC, J12934 commented on routes/basketItems.js
> +    const parser = clarinet.parser()
Can you extract the custom json parser out into a function?
Like "function ParseJsonCustom(jsonString)"?

2018-06-21 08:52 UTC, J12934 commented on routes/basketItems.js
> +    var productIds = []
This code is for adding multiple products to the basket right?
Is that even possible in the Application?

I guess the code would be much leaner if the code would just take one product.

2018-06-21 08:52 UTC, J12934 commented on server.js
> +app.use(function jsonParser (req, res, next) {
This custom bodyParser.json() implementation is for saving the body into rawBody right?
I guess we could do it like this, to keep using the functionality provided by bodyParser.
```js
app.use(bodyParser.text({type: '*/*'}))
app.use((req, res, next) => {
    req.rawBody = req.body()
    next()
})
app.use(bodyParser.json())
```

2018-06-22 09:12 UTC, CaptainFreak commented on routes/basketItems.js
> +    var productIds = []
No, @J12934 productId`s` is for storing multiple instancesof key which are in rawBody of POST, not for adding multiple products. It just takes the last value like JSON normally does. This POST endpoint exactly works like epilogue POST

2018-06-22 09:13 UTC, CaptainFreak commented on server.js
> +app.use(function jsonParser (req, res, next) {
I tried this but it doesnt work @J12934.

2018-06-22 09:26 UTC, J12934 commented on server.js
> +app.use(function jsonParser (req, res, next) {
Just tried it there was a slight error in the code i submitted it has to be `req.body` not `req.body()`.
Other than that it seems to work fine.

2018-06-22 09:45 UTC, CaptainFreak commented on server.js
> +app.use(function jsonParser (req, res, next) {
Oh can you confirm by running e2e test or something actually did tried it with `req.body
`

2018-06-22 10:05 UTC, J12934 commented on server.js
> +app.use(function jsonParser (req, res, next) {
Mh no your right tests are failing. I wonder why 🤔

2018-06-22 10:07 UTC, CaptainFreak commented on server.js
> +app.use(function jsonParser (req, res, next) {
Actually after using it, json doesn't get parsed I guess .. I tried logging in and it wasn't working so I confirmed it doesn't work.

2018-06-22 10:52 UTC, J12934 approved these changes

2018-06-22 10:53 UTC, merged