Exploit chain 1
juice-shop/juice-shop pull request #632
Opened 2018-07-05 07:19 UTC by CaptainFreak

This needs improvement regarding verification of challenge is solved or not and one client side unit test.
Please review @J12934 @wurstbrot @bkimminich :)

2018-07-05 08:49 UTC, J12934 commented
Hi Shoeb
will take a closer look at this later today.
But at first glance i noticed another security flaw in that code: 😉

An attacker can avoid the logging of his IP by never logging out.😅
It would be nice if we could make a challenge out of that (or a other way to prevent the ip logging), but that's also a pretty hard thing to verify whether it was solved or not

2018-07-05 08:57 UTC, CaptainFreak commented
Great, By the way I did not understand about security flaw of not logging out.

2018-07-05 09:11 UTC, J12934 commented
Well the IP just gets logged when the user clicks the logout button.
So, the IP logging as a protection / logging mechanism can be avoided by just not clicking the button.

2018-07-05 09:30 UTC, bkimminich commented
How about we put the last IP of a user on the administration page user list? That way it could be verified. Name of that challenge should involve the word "ninja"... 🤣

2018-07-05 17:26 UTC, wurstbrot requested changes
I have the following suggestions

2018-07-05 17:26 UTC, wurstbrot commented on app/js/services/LogoutService.js
> +  var host = '/rest/saveLoginIp'
Why is this variable named host?

2018-07-05 17:26 UTC, wurstbrot commented on models/user.js
> +      defaultValue: 'x.x.x.x'
I would prefer a number like 0.0.0.0 or 127.0.0.1

2018-07-05 17:26 UTC, wurstbrot commented on test/e2e/restApiSpec.js
> +    it('should be possible to save log-in IP when logged in', () => {
I wish a test like 'it should not be possible to save log-in IP when not logged in'

2018-07-07 07:25 UTC, shoebpate1 commented
Will get on it @wurstbrot , Any suggestion on how to pass the failing client side test ? @bkimminich @J12934

2018-07-10 05:31 UTC, CaptainFreak commented on app/js/services/LogoutService.js
> +  var host = '/rest/saveLoginIp'
host variable is used for base url in every servic.

2018-07-10 06:31 UTC, CaptainFreak commented on test/e2e/restApiSpec.js
> +    it('should be possible to save log-in IP when logged in', () => {
Wrote it :)

2018-07-11 07:50 UTC, bkimminich commented
@wurstbrot / @J12934, is this one ready from your point of view so we can merge it?

2018-07-11 08:54 UTC, J12934 commented
I don’t think it is ready yet.
We are still unsure about how to properly validate whether the challenge was solved or not. The current way only checks part of the challenge.

2018-07-12 06:37 UTC, merged