Issue #699
juice-shop/juice-shop pull request #798
Opened 2019-02-02 12:53 UTC by aaryan01

Added overwriteUrlForProductTamperingChallenge.
Refactored tests to make the URL and the overwrite URL configurable.
Changed http://kimminich.de to https://owasp.slack.com.

2019-02-02 18:00 UTC, J12934 requested changes
Looks good 👍
Just one tiny thing

2019-02-02 18:00 UTC, J12934 commented on routes/verify.js
> +    if (!utils.contains(osaft.description, `${config.get('products.8.urlForProductTamperingChallenge')}`)) {
This will not work for custom configs which have the "product for tampering challenge product" on a other index as `8`. This should instead do a search for the first product in the list with the `urlForProductTamperingChallenge` key set.

2019-02-02 18:00 UTC, J12934 commented on test/server/verifySpec.js
> +        products.osaft.description = `Vanilla O-Saft! <a href="${config.get('products.8.urlForProductTamperingChallenge')}" target="_blank">More...</a>`
Same thing here 😉

2019-02-02 19:01 UTC, bkimminich commented
@aaryan01, great job! Do you want to make the small improvements suggested by Jannik before we merge? As this is not critical for default usage we could also do it afterwards - up to you! 😀

2019-02-03 08:32 UTC, aaryan01 commented
@bkimminich @J12934 Travis seems to be throwing an error while running ```npm run build``` but it isn't showing up locally. Could you please check?

2019-02-03 10:39 UTC, J12934 approved these changes

2019-02-03 10:43 UTC, J12934 commented
Yeah there seems to be a bug in the newest version of a webpack plugin which makes the build fail.
@devanshbatra04 also ran into this, see: https://github.com/bkimminich/juice-shop/issues/789#issuecomment-459996389

I'm hoping this gets fixed soon, otherwise we can downgrade the dependency.

2019-02-03 13:52 UTC, bkimminich commented
I already tried pinning to 3.14.1 of the supposed culprit, but it didn't help. Travis still ran into error. Guess we'll sit it out until the dependency gets fixed hopefully on Monday. I won't merge any PRs until then as a precaution.

2019-02-04 13:50 UTC, merged