Check for port usage
juice-shop/juice-shop pull request #893
Opened 2019-03-23 12:37 UTC by agrawalarpit14

Check if port 3000 is available before running the juice-shop instance.
Part of #683

2019-03-23 12:40 UTC, agrawalarpit14 commented
Hi @bkimminich Can you please let me know how would the test for this be defined. 
- The issue is as it checks whether the port 3000 is in use or not. For the test to be valid the port should indeed be closed.
- Or otherwise, should I verify the test by any port that is closed than check both conditions, i.e, one when port is closed and other by opening a server on that port temporarily.

2019-03-23 15:29 UTC, J12934 requested changes

2019-03-23 15:29 UTC, J12934 commented on lib/startup/validatePreconditions.js
> +  if (!success && !portSuccess && exitOnFailure) {
The conditional isn't working as intended, this would only fail if both conditions and `exitOnFailure` are false.

2019-03-23 15:29 UTC, J12934 commented on lib/startup/validatePreconditions.js
> +  portscanner.checkPortStatus(port, function (status) {
This also doesn't work as intended. The `checkIfPortIsAvailable` will always return `undefined` as the returns are for the protscanner callback function not the `checkIfPortIsAvailable` function.

Best thing to do here is probably to wrap this in a promise, which you can then await in the validate function.

2019-03-23 15:32 UTC, J12934 commented
For adding a test do this i would recommend doing this in the server testing suite. There you can test `checkIfPortIsAvailable` in isolation. You can start a small server before the test and check if the function can detect it or not.

2019-03-24 11:13 UTC, agrawalarpit14 commented
Hi @J12934 Thank you very much for the review. I got to learn a lot from it. I have tried to implement code the way you suggested. Please have a look.
Thanks!!😁

2019-03-25 11:52 UTC, J12934 approved these changes
Nice 👍
Thank you for those changes!

I made some more small refactoring, see the comments on e35b92089683e7ab36ff474d465f7468a3e24acd
It's now ready to be merged in my opinion.

2019-03-25 12:51 UTC, merged

2019-03-25 14:21 UTC, bkimminich commented
Thanks! Just had to fix a massive issue that _would have_ occurred for all custom configs which are not using port 3000 ... ;-)